// Shared Equipment Data — PharmaExec MES
// Extracted from DataManager.tsx so BatchRecords and other modules can import
// equipment master data without circular dependencies.

import type {
  CleaningLevel,
  CleaningLogEntry,
  CleaningRule,
  ComparisonType,
  EquipmentType,
  GmpStatus,
  HealthStatus,
  MaintenanceStatus,
} from "./gmpValidation";

export type EntityType =
  | "WorkCenter"
  | "Room"
  | "Station"
  | "SubStation"
  | "EquipmentClass"
  | "EquipmentEntity"
  | "PropertyType"
  | "ProductMaster";

export interface ChangeEntry {
  timestamp: string;
  field: string;
  oldValue: string;
  newValue: string;
  changedBy: string;
  action?: "Create" | "Update" | "Delete";
  reason?: string;
}

// ── New MES types ─────────────────────────────────────────────────────────
export type EquipmentLogbookAction =
  | "Execution Start"
  | "Execution Stop"
  | "Cleaning"
  | "Pause"
  | "Resume"
  | "Status Change"
  | "Unbind";

export type RoomLogbookAction =
  | "Room Cleaning"
  | "Line Clearance"
  | "Area Status Change"
  | "Unbind";

export type LogbookAction = EquipmentLogbookAction | RoomLogbookAction;

export interface LogbookEntry {
  id: string;
  timestamp: string;
  user: string;
  action: LogbookAction;
  reason: string;
  statusChange?: string; // e.g. "Draft → Approved", "Approved → Executed"
  details?: string;
  entityType?: "Equipment" | "Room";
  entityIdentifier?: string;
}

export interface StatusHistoryEntry {
  timestamp: string;
  user: string;
  fromStatus: string;
  toStatus: string;
  reason: string;
}

export interface EquipmentNode {
  id: string;
  identifier: string;
  shortDescription: string;
  description: string;
  level: string;
  inventoryNumber: string;
  manufacturer: string;
  externalId: string;
  serialNumber: string;
  manufacturingDate: string;
  disposed: boolean;
  barcode: string;
  barcodeEnabled: boolean;
  entityType: EntityType;
  parentId: string | null;
  automationServerNameDefault: string;
  automationServerName: string;
  dataOpsPath: string;
  historianProvider: string;
  historianAccessServerDefault: string;
  historianAccessServer: string;
  historianServerDefault: string;
  historianServer: string;
  createdAt: string;
  changeHistory: ChangeEntry[];
  // GMP fields
  status?: GmpStatus;
  maintenance_status?: MaintenanceStatus;
  health_status?: HealthStatus;
  last_maintenance_date?: string;
  pm_due_date?: string;
  cleaningRules?: CleaningRule[];
  cleaningLog?: CleaningLogEntry | null;
  // PropertyType capability fields
  min_value?: string;
  max_value?: string;
  required_min?: string;
  required_max?: string;
  comparison_type?: ComparisonType | "";
  // Change Control fields
  versionNumber?: number;
  originalId?: string | null;
  revisedById?: string | null;
  changeControlReason?: string;
  // Lifecycle & Audit fields (added for MES refactor)
  createdBy?: string; // default 'System'
  updatedAt?: string; // ISO string
  isUsedInBatch?: boolean; // default false — locks Edit/Delete when true
  // Advanced Equipment Type & Hierarchy (pharma execution logic)
  equipmentType?: EquipmentType; // Fixed | Moveable
  roomId?: string; // linked Room id
  stationId?: string; // linked Station id
  subStationId?: string; // linked Sub-Station id
  // Advanced Cleaning fields
  cleaningStatus?: "Clean" | "Due" | "Expired";
  lastCleanedAt?: string; // ISO date string
  cleaningValidTill?: string; // ISO date string
  lastProductUsed?: string; // productCode
  cleaningReason?: string; // required for Fixed equipment
  currentCampaignBatches?: number; // batches completed in current campaign
  // Context tab fields
  currentBatchId?: string;
  currentBatchStatus?: string;
  lastBatch?: string;
  previousContext?: string; // stores the previous batch context
  lastExecutionDate?: string;
  // Specification simplified fields
  cleaningType?: "CIP" | "Manual" | "None";
  requiresCleaning?: boolean;
  // Room-specific cleaning & specification fields
  roomCleaningStatus?: "Clean" | "Required" | "Overdue";
  roomLastCleanedAt?: string; // ISO date
  roomCleaningValidTill?: string; // ISO date
  roomLastProduct?: string; // last product processed in room
  roomCleaningLevel?: "None" | "Minor" | "Major";
  roomCleaningType?: "CIP" | "Manual" | "Fogging" | "None";
  roomRequiresCleaning?: boolean;
  roomCleanRoomClass?: string; // e.g. "ISO 7", "ISO 8"
  roomType?: string; // e.g. "Solid Dosage", "Coating", "Granulation"
  roomCleaningFrequency?: string; // e.g. "After each batch", "Weekly"
  // New tracking structures
  logbookEntries?: LogbookEntry[];
  statusHistory?: StatusHistoryEntry[];
}

export const INITIAL_DATA: EquipmentNode[] = [
  {
    id: "wc1",
    identifier: "WC-COAT-001",
    shortDescription: "W&C Coater",
    description: "Coating Unit Work Center — primary film-coating line",
    level: "1",
    inventoryNumber: "INV-2021-0441",
    manufacturer: "Pharma Machines Ltd",
    externalId: "WC001",
    serialNumber: "PML-2021-C001",
    manufacturingDate: "2021-03-15",
    disposed: false,
    barcode: "BC-WC-001",
    barcodeEnabled: true,
    entityType: "WorkCenter",
    parentId: null,
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "AIS-COAT-01",
    dataOpsPath: "/pharma/coating/wc001",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "PI-COAT-01",
    historianServerDefault: "PIServer1",
    historianServer: "PI-MAIN",
    createdAt: "2024-01-10T08:00:00Z",
    changeHistory: [
      {
        timestamp: "2024-06-12T14:32:00Z",
        field: "automationServerName",
        oldValue: "AIS-OLD",
        newValue: "AIS-COAT-01",
        changedBy: "Dr. Sarah Chen",
      },
    ],
    status: "Approved",
  },
  {
    id: "wc2",
    identifier: "WC-COAT-002",
    shortDescription: "W&C Coater-A",
    description: "Coating Unit Work Center — automated secondary line",
    level: "1",
    inventoryNumber: "INV-2022-0552",
    manufacturer: "Pharma Machines Ltd",
    externalId: "WC002",
    serialNumber: "PML-2022-C002",
    manufacturingDate: "2022-07-20",
    disposed: false,
    barcode: "BC-WC-002",
    barcodeEnabled: true,
    entityType: "WorkCenter",
    parentId: null,
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "AIS-COAT-02",
    dataOpsPath: "/pharma/coating/wc002",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "PI-COAT-02",
    historianServerDefault: "PIServer1",
    historianServer: "PI-MAIN",
    createdAt: "2024-01-10T08:30:00Z",
    changeHistory: [],
    status: "Draft",
  },
  {
    id: "sta1",
    identifier: "STA-FEED-001",
    shortDescription: "Sta Feeder",
    description: "Coating Unit Feeder Station",
    level: "2",
    inventoryNumber: "INV-2021-0442",
    manufacturer: "Fluid Air Inc",
    externalId: "STA001",
    serialNumber: "FAI-2021-F001",
    manufacturingDate: "2021-04-10",
    disposed: false,
    barcode: "BC-STA-001",
    barcodeEnabled: true,
    entityType: "Station",
    parentId: "wc1",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/coating/wc001/feeder",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-11T09:00:00Z",
    changeHistory: [],
    status: "Approved",
  },
  {
    id: "sta2",
    identifier: "STA-FEED-002",
    shortDescription: "Sta Feeder-A",
    description: "Coating Unit Feeder Duplicate Station",
    level: "2",
    inventoryNumber: "INV-2021-0443",
    manufacturer: "Fluid Air Inc",
    externalId: "STA002",
    serialNumber: "FAI-2021-F002",
    manufacturingDate: "2021-04-12",
    disposed: false,
    barcode: "BC-STA-002",
    barcodeEnabled: true,
    entityType: "Station",
    parentId: "wc1",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "AIS-FEED-02",
    dataOpsPath: "/pharma/coating/wc001/feeder-a",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-11T09:15:00Z",
    changeHistory: [],
    status: "Draft",
  },
  {
    id: "sta3",
    identifier: "STA-VESS-001",
    shortDescription: "Sta Vessel",
    description: "Coating Unit Vessel Station",
    level: "2",
    inventoryNumber: "INV-2021-0444",
    manufacturer: "Pharma Machines Ltd",
    externalId: "STA003",
    serialNumber: "PML-2021-V001",
    manufacturingDate: "2021-04-15",
    disposed: false,
    barcode: "BC-STA-003",
    barcodeEnabled: false,
    entityType: "Station",
    parentId: "wc1",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/coating/wc001/vessel",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-11T09:30:00Z",
    changeHistory: [],
    status: "Approved",
  },
  {
    id: "sta4",
    identifier: "STA-VESS-002",
    shortDescription: "Sta Vessel-A",
    description: "Coating Unit Vessel Automated Station",
    level: "2",
    inventoryNumber: "INV-2022-0553",
    manufacturer: "Pharma Machines Ltd",
    externalId: "STA004",
    serialNumber: "PML-2022-V002",
    manufacturingDate: "2022-08-01",
    disposed: false,
    barcode: "BC-STA-004",
    barcodeEnabled: true,
    entityType: "Station",
    parentId: "wc2",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "AIS-VESS-02",
    dataOpsPath: "/pharma/coating/wc002/vessel-a",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "PI-VESS-02",
    historianServerDefault: "PIServer1",
    historianServer: "PI-MAIN",
    createdAt: "2024-01-11T10:00:00Z",
    changeHistory: [],
    status: "Approved",
  },
  {
    id: "ec1",
    identifier: "EC-COAT-001",
    shortDescription: "Coaters",
    description: "Non-automated coating equipment class",
    level: "1",
    inventoryNumber: "INV-CLASS-001",
    manufacturer: "Pharma Machines Ltd",
    externalId: "EC001",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "",
    barcodeEnabled: false,
    entityType: "EquipmentClass",
    parentId: null,
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/classes/coaters",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-05T07:00:00Z",
    changeHistory: [],
    status: "Approved",
    maintenance_status: "Active",
    health_status: "Good",
    pm_due_date: "2026-06-01",
    cleaningRules: [],
    cleaningLog: null,
  },
  {
    id: "ec2",
    identifier: "EC-COAT-002",
    shortDescription: "Coaters-A",
    description: "Automated coating equipment class",
    level: "1",
    inventoryNumber: "INV-CLASS-002",
    manufacturer: "Pharma Machines Ltd",
    externalId: "EC002",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "",
    barcodeEnabled: false,
    entityType: "EquipmentClass",
    parentId: null,
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "AIS-CLASS-02",
    dataOpsPath: "/pharma/classes/coaters-a",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-05T07:30:00Z",
    changeHistory: [],
    status: "Approved",
    maintenance_status: "Active",
    health_status: "Good",
    pm_due_date: "2026-07-15",
    cleaningRules: [],
    cleaningLog: null,
  },
  // ee1: Executed + isUsedInBatch — terminal lock demo
  {
    id: "ee1",
    identifier: "EE-COAT-S",
    shortDescription: "Coater_S",
    description:
      "Small non-automated coating unit — currently in active batch B-2026-001 (Amoxicillin)",
    level: "2",
    inventoryNumber: "INV-2020-0310",
    manufacturer: "Pharma Machines Ltd",
    externalId: "EE001",
    serialNumber: "PML-2020-CS01",
    manufacturingDate: "2020-05-20",
    disposed: false,
    barcode: "BC-EE-001",
    barcodeEnabled: true,
    entityType: "EquipmentEntity",
    parentId: "ec1",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/equipment/coater-s",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-12T08:00:00Z",
    createdBy: "Dr. Sarah Chen",
    updatedAt: "2026-04-01T10:00:00Z",
    changeHistory: [
      {
        timestamp: "2026-04-01T10:00:00Z",
        field: "status",
        oldValue: "Approved",
        newValue: "Executed",
        changedBy: "Dr. Sarah Chen",
        action: "Update",
        reason: "Batch Execution B-2026-001 confirmed",
      },
    ],
    status: "Executed",
    isUsedInBatch: true,
    maintenance_status: "Active",
    health_status: "Good",
    last_maintenance_date: "2025-12-01",
    pm_due_date: "2026-06-01",
    cleaningRules: [],
    cleaningLog: {
      lastProduct: "Amoxicillin 250mg",
      lastCleanedDate: "2026-03-20",
      cleaningLevel: "Major",
      cleaningReason: "Product changeover - end of campaign",
    },
    equipmentType: "Fixed",
    roomId: "room_001",
    stationId: "sta3",
    subStationId: "subst_001",
    cleaningStatus: "Clean",
    lastCleanedAt: "2026-03-20T08:00:00Z",
    cleaningValidTill: "2026-04-20T08:00:00Z",
    lastProductUsed: "PRD-AMX-001",
    cleaningReason: "Product changeover - end of Amoxicillin campaign",
    currentCampaignBatches: 5,
    // Context tab
    currentBatchId: "B-2026-001",
    currentBatchStatus: "In Process",
    lastBatch: "B-2025-042",
    lastExecutionDate: "2026-03-20",
    // Specification simplified
    cleaningType: "CIP",
    requiresCleaning: true,
    // Logbook — rich entries with new action types
    logbookEntries: [
      {
        id: "lb-ee1-1",
        timestamp: "2026-03-18T07:15:00Z",
        user: "Operator J. Patel",
        action: "Execution Start",
        reason: "Batch B-2026-001 started — Amoxicillin 250mg film coating",
        statusChange: "Approved → Executed",
        details: "Recipe RC-AMX-FC-001 v3",
      },
      {
        id: "lb-ee1-2",
        timestamp: "2026-03-18T11:30:00Z",
        user: "Operator J. Patel",
        action: "Pause",
        reason: "Scheduled break — equipment cooling required",
      },
      {
        id: "lb-ee1-3",
        timestamp: "2026-03-18T12:45:00Z",
        user: "Operator J. Patel",
        action: "Resume",
        reason: "Cooling complete, resumed coating process",
      },
      {
        id: "lb-ee1-4",
        timestamp: "2026-03-19T16:00:00Z",
        user: "Dr. Sarah Chen",
        action: "Execution Stop",
        reason: "Batch B-2026-001 coating complete",
        statusChange: "Executed → Approved",
      },
      {
        id: "lb-ee1-5",
        timestamp: "2026-03-20T08:00:00Z",
        user: "Dr. Sarah Chen",
        action: "Cleaning",
        reason: "Major CIP cleaning after Amoxicillin campaign",
        details: "CIP Level: Major, Valid till 2026-04-20",
      },
    ],
    // Status history
    statusHistory: [
      {
        timestamp: "2025-06-01T09:00:00Z",
        user: "Dr. Sarah Chen",
        fromStatus: "Draft",
        toStatus: "Approved",
        reason: "Initial qualification complete, GMP approved",
      },
      {
        timestamp: "2026-04-01T10:00:00Z",
        user: "Dr. Sarah Chen",
        fromStatus: "Approved",
        toStatus: "Executed",
        reason: "Batch Execution B-2026-001 confirmed",
      },
    ],
  },
  // ee2: Draft, Active, Good, PM Due Soon — yellow
  {
    id: "ee2",
    identifier: "EE-COAT-M",
    shortDescription: "Coater_M",
    description: "Medium non-automated coating unit",
    level: "2",
    inventoryNumber: "INV-2020-0311",
    manufacturer: "Pharma Machines Ltd",
    externalId: "EE002",
    serialNumber: "PML-2020-CM01",
    manufacturingDate: "2020-06-10",
    disposed: false,
    barcode: "BC-EE-002",
    barcodeEnabled: true,
    entityType: "EquipmentEntity",
    parentId: "ec1",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/equipment/coater-m",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-12T08:15:00Z",
    changeHistory: [],
    status: "Draft",
    maintenance_status: "Active",
    health_status: "Good",
    last_maintenance_date: "2025-11-15",
    pm_due_date: "2026-04-09",
    cleaningRules: [],
    cleaningLog: null,
    // Context tab
    lastBatch: "B-2025-031",
    lastExecutionDate: "2026-01-15",
    // Specification simplified
    cleaningType: "Manual",
    requiresCleaning: true,
    // Logbook
    logbookEntries: [
      {
        id: "lb-ee2-1",
        timestamp: "2026-01-14T08:00:00Z",
        user: "Operator M. Torres",
        action: "Execution Start",
        reason: "Batch B-2025-031 Metformin 500mg coating",
        statusChange: "Draft → Approved",
      },
      {
        id: "lb-ee2-2",
        timestamp: "2026-01-15T14:30:00Z",
        user: "Operator M. Torres",
        action: "Execution Stop",
        reason: "Batch B-2025-031 complete",
      },
      {
        id: "lb-ee2-3",
        timestamp: "2026-01-16T09:00:00Z",
        user: "Operator M. Torres",
        action: "Cleaning",
        reason: "Manual cleaning between batches",
      },
    ],
    // Status history
    statusHistory: [
      {
        timestamp: "2025-09-10T10:00:00Z",
        user: "Dr. Sarah Chen",
        fromStatus: "Approved",
        toStatus: "Draft",
        reason: "Converted to Draft for PM schedule update",
      },
    ],
  },
  // ee3: Approved, Under Maintenance, Bad, PM Overdue — red
  {
    id: "ee3",
    identifier: "EE-COAT-N",
    shortDescription: "Coater_N",
    description: "Nano non-automated coating unit",
    level: "2",
    inventoryNumber: "INV-2021-0315",
    manufacturer: "Fluid Air Inc",
    externalId: "EE003",
    serialNumber: "FAI-2021-CN01",
    manufacturingDate: "2021-01-25",
    disposed: false,
    barcode: "BC-EE-003",
    barcodeEnabled: false,
    entityType: "EquipmentEntity",
    parentId: "ec1",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/equipment/coater-n",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-12T08:30:00Z",
    changeHistory: [],
    status: "Approved",
    maintenance_status: "Under Maintenance",
    health_status: "Bad",
    last_maintenance_date: "2025-09-10",
    pm_due_date: "2026-03-15",
    cleaningRules: [],
    cleaningLog: null,
    equipmentType: "Moveable",
    roomId: "room_002",
    stationId: "sta3",
    subStationId: "subst_002",
    cleaningStatus: "Expired",
    lastCleanedAt: "2026-01-01T08:00:00Z",
    cleaningValidTill: "2026-01-03T08:00:00Z",
    lastProductUsed: "PRD-OMP-003",
    currentCampaignBatches: 4,
    // Context tab
    lastBatch: "B-2025-028",
    lastExecutionDate: "2025-12-10",
    // Specification simplified
    cleaningType: "CIP",
    requiresCleaning: true,
    // Logbook
    logbookEntries: [
      {
        id: "lb-ee3-1",
        timestamp: "2025-12-08T09:00:00Z",
        user: "Operator K. Sharma",
        action: "Execution Start",
        reason: "Batch B-2025-028 Omeprazole coating",
        statusChange: "Draft → Approved",
      },
      {
        id: "lb-ee3-2",
        timestamp: "2025-12-09T14:00:00Z",
        user: "Operator K. Sharma",
        action: "Pause",
        reason: "Equipment issue — spray nozzle blockage",
      },
      {
        id: "lb-ee3-3",
        timestamp: "2025-12-10T11:00:00Z",
        user: "Operator K. Sharma",
        action: "Execution Stop",
        reason: "Batch aborted — equipment under maintenance",
        statusChange: "Approved → Under Maintenance",
      },
      {
        id: "lb-ee3-4",
        timestamp: "2026-01-01T08:00:00Z",
        user: "Maintenance Team",
        action: "Cleaning",
        reason: "Pre-maintenance CIP cleaning",
      },
    ],
    // Status history
    statusHistory: [
      {
        timestamp: "2024-08-15T08:00:00Z",
        user: "Dr. Sarah Chen",
        fromStatus: "Draft",
        toStatus: "Approved",
        reason: "GMP qualification approved after calibration",
      },
      {
        timestamp: "2026-03-20T09:00:00Z",
        user: "Engineer R. Patel",
        fromStatus: "Approved",
        toStatus: "Approved",
        reason: "Placed Under Maintenance — PM overdue, cleaning expired",
      },
    ],
  },
  // ee4: Approved, Active, Good, PM OK, cleaning Required — red
  {
    id: "ee4",
    identifier: "EE-COAT-AT",
    shortDescription: "Coater_At",
    description: "Automated tablet coating unit",
    level: "2",
    inventoryNumber: "INV-2022-0560",
    manufacturer: "GEA Pharma Systems",
    externalId: "EE004",
    serialNumber: "GEA-2022-AT01",
    manufacturingDate: "2022-03-14",
    disposed: false,
    barcode: "BC-EE-004",
    barcodeEnabled: true,
    entityType: "EquipmentEntity",
    parentId: "ec2",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "AIS-EE-04",
    dataOpsPath: "/pharma/equipment/coater-at",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "PI-EE-04",
    historianServerDefault: "PIServer1",
    historianServer: "PI-MAIN",
    createdAt: "2024-01-12T09:00:00Z",
    changeHistory: [],
    status: "Approved",
    isUsedInBatch: true,
    createdBy: "Dr. Sarah Chen",
    updatedAt: "2026-03-28T11:00:00Z",
    maintenance_status: "Active",
    health_status: "Good",
    last_maintenance_date: "2026-01-20",
    pm_due_date: "2026-07-20",
    cleaningRules: [
      {
        id: "cr1",
        previousProduct: "Amoxicillin 500mg",
        nextProduct: "Metformin 500mg",
        requiredCleaningLevel: "Major",
      },
      {
        id: "cr2",
        previousProduct: "Ciprofloxacin 500mg",
        nextProduct: "Paracetamol 500mg",
        requiredCleaningLevel: "Minor",
      },
    ],
    cleaningLog: {
      lastProduct: "Amoxicillin 500mg",
      lastCleanedDate: "2026-03-28",
      cleaningLevel: "Minor",
    },
    equipmentType: "Fixed",
    roomId: "room_001",
    stationId: "sta4",
    subStationId: "subst_003",
    cleaningStatus: "Due",
    lastCleanedAt: "2026-03-28T07:00:00Z",
    cleaningValidTill: "2026-04-06T07:00:00Z",
    lastProductUsed: "PRD-AMX-001",
    cleaningReason: "Routine inter-batch cleaning",
    currentCampaignBatches: 3,
    // Context tab
    currentBatchId: "B-2026-003",
    currentBatchStatus: "Released",
    lastBatch: "B-2026-001",
    lastExecutionDate: "2026-03-28",
    // Specification simplified
    cleaningType: "CIP",
    requiresCleaning: true,
    // Logbook
    logbookEntries: [
      {
        id: "lb-ee4-1",
        timestamp: "2026-03-26T07:00:00Z",
        user: "Operator J. Patel",
        action: "Execution Start",
        reason: "Batch B-2026-003 Atorvastatin coating started",
        statusChange: "Approved → Executed",
        details: "Auto-coater recipe v2",
      },
      {
        id: "lb-ee4-2",
        timestamp: "2026-03-27T10:00:00Z",
        user: "Operator J. Patel",
        action: "Pause",
        reason: "Mid-batch inspection hold",
      },
      {
        id: "lb-ee4-3",
        timestamp: "2026-03-27T11:30:00Z",
        user: "QA Dr. R. Mehta",
        action: "Resume",
        reason: "Inspection passed, resumed",
      },
      {
        id: "lb-ee4-4",
        timestamp: "2026-03-28T15:00:00Z",
        user: "Dr. Sarah Chen",
        action: "Execution Stop",
        reason: "Batch B-2026-003 released",
        statusChange: "Executed → Approved",
      },
      {
        id: "lb-ee4-5",
        timestamp: "2026-03-28T16:00:00Z",
        user: "Operator J. Patel",
        action: "Cleaning",
        reason: "Inter-batch CIP — minor level",
      },
    ],
    // Status history
    statusHistory: [
      {
        timestamp: "2024-03-10T10:00:00Z",
        user: "Dr. Sarah Chen",
        fromStatus: "Draft",
        toStatus: "Approved",
        reason: "GMP validation passed, IQ/OQ/PQ complete",
      },
      {
        timestamp: "2026-01-20T09:00:00Z",
        user: "Engineer R. Patel",
        fromStatus: "Approved",
        toStatus: "Draft",
        reason: "PM maintenance window — temporary draft for PM update",
      },
    ],
  },
  // ee5: Executed, Active, Good, PM OK, cleaning OK — green
  {
    id: "ee5",
    identifier: "EE-COAT-AM",
    shortDescription: "Coater_AM",
    description: "Automated membrane coating unit",
    level: "2",
    inventoryNumber: "INV-2022-0561",
    manufacturer: "GEA Pharma Systems",
    externalId: "EE005",
    serialNumber: "GEA-2022-AM01",
    manufacturingDate: "2022-04-08",
    disposed: false,
    barcode: "BC-EE-005",
    barcodeEnabled: true,
    entityType: "EquipmentEntity",
    parentId: "ec2",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "AIS-EE-05",
    dataOpsPath: "/pharma/equipment/coater-am",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "PI-EE-05",
    historianServerDefault: "PIServer1",
    historianServer: "PI-MAIN",
    createdAt: "2024-01-12T09:15:00Z",
    changeHistory: [],
    status: "Executed",
    isUsedInBatch: false,
    createdBy: "Dr. Sarah Chen",
    updatedAt: "2026-03-15T09:00:00Z",
    maintenance_status: "Active",
    health_status: "Good",
    last_maintenance_date: "2026-02-10",
    pm_due_date: "2026-08-10",
    cleaningRules: [],
    cleaningLog: {
      lastProduct: "Paracetamol 500mg",
      lastCleanedDate: "2026-03-30",
      cleaningLevel: "Major",
      cleaningReason: "Major cleaning after Paracetamol campaign",
    },
    equipmentType: "Moveable",
    roomId: "room_002",
    stationId: "sta4",
    cleaningStatus: "Clean",
    lastCleanedAt: "2026-03-30T09:00:00Z",
    cleaningValidTill: "2026-04-30T09:00:00Z",
    lastProductUsed: "PRD-MET-002",
    currentCampaignBatches: 2,
    // Context tab
    currentBatchId: "B-2026-002",
    currentBatchStatus: "Completed",
    lastBatch: "B-2025-040",
    lastExecutionDate: "2026-03-15",
    // Specification simplified
    cleaningType: "Manual",
    requiresCleaning: false,
    // Logbook
    logbookEntries: [
      {
        id: "lb-ee5-1",
        timestamp: "2026-03-13T08:00:00Z",
        user: "Operator M. Torres",
        action: "Execution Start",
        reason: "Batch B-2026-002 Paracetamol membrane coating",
        statusChange: "Approved → Executed",
      },
      {
        id: "lb-ee5-2",
        timestamp: "2026-03-15T12:00:00Z",
        user: "Operator M. Torres",
        action: "Execution Stop",
        reason: "Batch B-2026-002 completed",
        statusChange: "Executed → Approved",
      },
      {
        id: "lb-ee5-3",
        timestamp: "2026-03-15T14:00:00Z",
        user: "Dr. Sarah Chen",
        action: "Cleaning",
        reason: "Major cleaning — Paracetamol campaign end",
        details: "Valid till 2026-04-30",
      },
    ],
    // Status history
    statusHistory: [
      {
        timestamp: "2024-04-20T10:00:00Z",
        user: "Dr. Sarah Chen",
        fromStatus: "Draft",
        toStatus: "Approved",
        reason: "Initial GMP qualification complete",
      },
      {
        timestamp: "2026-01-05T11:00:00Z",
        user: "Operator B. Nguyen",
        fromStatus: "Approved",
        toStatus: "Draft",
        reason: "Re-qualification after equipment relocation",
      },
      {
        timestamp: "2026-03-15T09:00:00Z",
        user: "Dr. Sarah Chen",
        fromStatus: "Draft",
        toStatus: "Executed",
        reason: "Batch B-2026-002 executed successfully",
      },
    ],
  },
  // ee6: Approved, Active, Bad, PM Overdue — red
  {
    id: "ee6",
    identifier: "EE-COAT-AK",
    shortDescription: "Coater_Ak",
    description: "Automated kinetic coating unit",
    level: "2",
    inventoryNumber: "INV-2023-0600",
    manufacturer: "GEA Pharma Systems",
    externalId: "EE006",
    serialNumber: "GEA-2023-AK01",
    manufacturingDate: "2023-01-30",
    disposed: false,
    barcode: "BC-EE-006",
    barcodeEnabled: true,
    entityType: "EquipmentEntity",
    parentId: "ec2",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "AIS-EE-06",
    dataOpsPath: "/pharma/equipment/coater-ak",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "PI-EE-06",
    historianServerDefault: "PIServer1",
    historianServer: "PI-MAIN",
    createdAt: "2024-01-12T09:30:00Z",
    changeHistory: [],
    status: "Approved",
    maintenance_status: "Active",
    health_status: "Bad",
    last_maintenance_date: "2025-08-01",
    pm_due_date: "2026-02-28",
    cleaningRules: [],
    cleaningLog: null,
    equipmentType: "Fixed",
    roomId: "room_002",
    stationId: "sta4",
    cleaningStatus: "Expired",
    lastCleanedAt: "2026-02-01T08:00:00Z",
    cleaningValidTill: "2026-02-03T08:00:00Z",
    lastProductUsed: "PRD-CIP-005",
    currentCampaignBatches: 3,
    // Context tab
    lastBatch: "B-2025-050",
    lastExecutionDate: "2026-02-01",
    // Specification simplified
    cleaningType: "CIP",
    requiresCleaning: true,
    // Logbook
    logbookEntries: [
      {
        id: "lb-ee6-1",
        timestamp: "2026-01-30T07:30:00Z",
        user: "Operator K. Sharma",
        action: "Execution Start",
        reason: "Batch B-2025-050 Ciprofloxacin coating",
        statusChange: "Draft → Approved",
      },
      {
        id: "lb-ee6-2",
        timestamp: "2026-02-01T16:00:00Z",
        user: "Operator K. Sharma",
        action: "Execution Stop",
        reason: "Batch complete",
      },
      {
        id: "lb-ee6-3",
        timestamp: "2026-02-01T17:00:00Z",
        user: "Maintenance Team",
        action: "Cleaning",
        reason: "Post-batch CIP cleaning — Minor level",
        details: "Valid till 2026-02-03 (expired)",
      },
    ],
    // Status history
    statusHistory: [
      {
        timestamp: "2024-05-15T10:00:00Z",
        user: "Dr. Sarah Chen",
        fromStatus: "Draft",
        toStatus: "Approved",
        reason: "IQ/OQ/PQ validation complete, equipment qualified",
      },
    ],
  },
  {
    id: "pt1",
    identifier: "PT-BATCHID",
    shortDescription: "Batch ID",
    description: "Unique batch identifier property type",
    level: "1",
    inventoryNumber: "",
    manufacturer: "",
    externalId: "PT001",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "",
    barcodeEnabled: false,
    entityType: "PropertyType",
    parentId: null,
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/properties/batch-id",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-08T10:00:00Z",
    changeHistory: [],
    status: "Approved",
    min_value: "",
    max_value: "",
    required_min: "",
    required_max: "",
    comparison_type: "",
  },
  {
    id: "pt2",
    identifier: "PT-COATPREP",
    shortDescription: "Coater Prepared",
    description: "Flag indicating coater has been prepared for batch",
    level: "1",
    inventoryNumber: "",
    manufacturer: "",
    externalId: "PT002",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "",
    barcodeEnabled: false,
    entityType: "PropertyType",
    parentId: null,
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/properties/coater-prepared",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-08T10:15:00Z",
    changeHistory: [],
    status: "Approved",
    min_value: "",
    max_value: "",
    required_min: "",
    required_max: "",
    comparison_type: "",
  },
  {
    id: "pt3",
    identifier: "PT-DRUMSIZE",
    shortDescription: "Drum Size",
    description: "Coating drum volume in litres",
    level: "1",
    inventoryNumber: "",
    manufacturer: "",
    externalId: "PT003",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "",
    barcodeEnabled: false,
    entityType: "PropertyType",
    parentId: null,
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/properties/drum-size",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-08T10:30:00Z",
    changeHistory: [],
    status: "Draft",
    min_value: "10",
    max_value: "200",
    required_min: "50",
    required_max: "150",
    comparison_type: "WITHIN_RANGE",
  },
  // Room nodes — top of location hierarchy
  {
    id: "room_001",
    identifier: "RM-MFG-01",
    shortDescription: "Manufacturing Room A",
    description: "Primary solid dosage manufacturing area — ISO 8 clean room",
    level: "0",
    inventoryNumber: "INV-RM-001",
    manufacturer: "Facility",
    externalId: "RM001",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "BC-RM-001",
    barcodeEnabled: false,
    entityType: "Room",
    parentId: null,
    automationServerNameDefault: "",
    automationServerName: "",
    dataOpsPath: "/pharma/rooms/mfg-a",
    historianProvider: "",
    historianAccessServerDefault: "",
    historianAccessServer: "",
    historianServerDefault: "",
    historianServer: "",
    createdAt: "2024-01-01T08:00:00Z",
    changeHistory: [],
    status: "Approved",
    roomCleaningStatus: "Clean",
    roomLastCleanedAt: "2026-03-20T09:00:00Z",
    roomCleaningValidTill: "2026-04-20T09:00:00Z",
    roomLastProduct: "AMOX-500",
    roomCleaningLevel: "Major",
    roomCleaningType: "CIP",
    roomRequiresCleaning: true,
    roomCleanRoomClass: "ISO 8",
    roomType: "Solid Dosage",
    roomCleaningFrequency: "After each batch",
    logbookEntries: [
      {
        id: "lb-rm1-1",
        timestamp: "2026-03-10T06:00:00Z",
        user: "Operator J. Patel",
        action: "Room Cleaning",
        reason: "Scheduled ISO 8 clean room deep clean before new campaign",
        entityType: "Room",
        entityIdentifier: "RM-MFG-01",
        details: "Cleaning agent: IPA 70% + disinfectant cycle",
      },
      {
        id: "lb-rm1-2",
        timestamp: "2026-03-10T09:30:00Z",
        user: "QA Officer R. Mehta",
        action: "Line Clearance",
        reason: "Pre-batch line clearance for Amoxicillin campaign",
        entityType: "Room",
        entityIdentifier: "RM-MFG-01",
        details: "LC-2026-031 approved — no previous product residue found",
      },
      {
        id: "lb-rm1-3",
        timestamp: "2026-03-18T07:00:00Z",
        user: "Supervisor A. Kumar",
        action: "Area Status Change",
        reason: "Room status changed to In-Use for Batch B-2026-001",
        entityType: "Room",
        entityIdentifier: "RM-MFG-01",
        statusChange: "Clean → In-Use",
      },
      {
        id: "lb-rm1-4",
        timestamp: "2026-03-19T17:00:00Z",
        user: "Supervisor A. Kumar",
        action: "Area Status Change",
        reason: "Batch B-2026-001 complete, room released for cleaning",
        entityType: "Room",
        entityIdentifier: "RM-MFG-01",
        statusChange: "In-Use → Cleaning Required",
      },
      {
        id: "lb-rm1-5",
        timestamp: "2026-03-20T09:00:00Z",
        user: "Operator J. Patel",
        action: "Room Cleaning",
        reason: "Post-batch cleaning — Amoxicillin residue removal",
        entityType: "Room",
        entityIdentifier: "RM-MFG-01",
        details: "CIP Level: Major, Valid till 2026-04-20",
      },
    ],
    statusHistory: [
      {
        timestamp: "2024-01-01T08:00:00Z",
        user: "Facility Manager",
        fromStatus: "Draft",
        toStatus: "Approved",
        reason: "Initial GMP qualification and ISO certification complete",
      },
    ],
  },
  {
    id: "room_002",
    identifier: "RM-MFG-02",
    shortDescription: "Manufacturing Room B",
    description: "Secondary coating and granulation area — ISO 7 clean room",
    level: "0",
    inventoryNumber: "INV-RM-002",
    manufacturer: "Facility",
    externalId: "RM002",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "BC-RM-002",
    barcodeEnabled: false,
    entityType: "Room",
    parentId: null,
    automationServerNameDefault: "",
    automationServerName: "",
    dataOpsPath: "/pharma/rooms/mfg-b",
    historianProvider: "",
    historianAccessServerDefault: "",
    historianAccessServer: "",
    historianServerDefault: "",
    historianServer: "",
    createdAt: "2024-01-01T08:00:00Z",
    changeHistory: [],
    status: "Approved",
    roomCleaningStatus: "Required",
    roomLastCleanedAt: "2026-03-06T10:00:00Z",
    roomCleaningValidTill: "2026-03-31T10:00:00Z",
    roomLastProduct: "MET-850",
    roomCleaningLevel: "Major",
    roomCleaningType: "Fogging",
    roomRequiresCleaning: true,
    roomCleanRoomClass: "ISO 7",
    roomType: "Coating & Granulation",
    roomCleaningFrequency: "After each batch",
    logbookEntries: [
      {
        id: "lb-rm2-1",
        timestamp: "2026-02-15T06:30:00Z",
        user: "Operator S. Rajan",
        action: "Line Clearance",
        reason: "Pre-campaign line clearance for Metformin granulation",
        entityType: "Room",
        entityIdentifier: "RM-MFG-02",
        details: "LC-2026-018 approved — all previous materials cleared",
      },
      {
        id: "lb-rm2-2",
        timestamp: "2026-02-15T08:00:00Z",
        user: "Supervisor M. Torres",
        action: "Area Status Change",
        reason: "Room activated for Metformin coating campaign",
        entityType: "Room",
        entityIdentifier: "RM-MFG-02",
        statusChange: "Clean → In-Use",
      },
      {
        id: "lb-rm2-3",
        timestamp: "2026-03-05T16:00:00Z",
        user: "QA Officer R. Mehta",
        action: "Area Status Change",
        reason:
          "Campaign complete, area placed under quarantine pending QA review",
        entityType: "Room",
        entityIdentifier: "RM-MFG-02",
        statusChange: "In-Use → Quarantine",
      },
      {
        id: "lb-rm2-4",
        timestamp: "2026-03-06T10:00:00Z",
        user: "Operator S. Rajan",
        action: "Room Cleaning",
        reason: "Full clean room sanitisation — post-campaign decontamination",
        entityType: "Room",
        entityIdentifier: "RM-MFG-02",
        details: "ISO 7 protocol applied, fogging with H2O2 vapour",
      },
      {
        id: "lb-rm2-5",
        timestamp: "2026-03-07T08:00:00Z",
        user: "QA Officer R. Mehta",
        action: "Area Status Change",
        reason: "QA environmental swab results clean — room released",
        entityType: "Room",
        entityIdentifier: "RM-MFG-02",
        statusChange: "Quarantine → Clean",
      },
    ],
    statusHistory: [
      {
        timestamp: "2024-01-01T08:00:00Z",
        user: "Facility Manager",
        fromStatus: "Draft",
        toStatus: "Approved",
        reason: "Initial GMP qualification and ISO 7 certification complete",
      },
    ],
  },
  // SubStation nodes — between Station and Equipment
  {
    id: "subst_001",
    identifier: "SS-COAT-01A",
    shortDescription: "Coating Sub-Station A",
    description: "Sub-station for drum loading and spray system",
    level: "3",
    inventoryNumber: "INV-SS-001",
    manufacturer: "Pharma Machines Ltd",
    externalId: "SS001",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "BC-SS-001",
    barcodeEnabled: false,
    entityType: "SubStation",
    parentId: "sta3",
    automationServerNameDefault: "",
    automationServerName: "",
    dataOpsPath: "/pharma/coating/wc001/vessel/ss-a",
    historianProvider: "",
    historianAccessServerDefault: "",
    historianAccessServer: "",
    historianServerDefault: "",
    historianServer: "",
    createdAt: "2024-01-01T08:00:00Z",
    changeHistory: [],
    status: "Approved",
  },
  {
    id: "subst_002",
    identifier: "SS-COAT-01B",
    shortDescription: "Coating Sub-Station B",
    description: "Sub-station for air handling and exhaust",
    level: "3",
    inventoryNumber: "INV-SS-002",
    manufacturer: "Pharma Machines Ltd",
    externalId: "SS002",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "BC-SS-002",
    barcodeEnabled: false,
    entityType: "SubStation",
    parentId: "sta3",
    automationServerNameDefault: "",
    automationServerName: "",
    dataOpsPath: "/pharma/coating/wc001/vessel/ss-b",
    historianProvider: "",
    historianAccessServerDefault: "",
    historianAccessServer: "",
    historianServerDefault: "",
    historianServer: "",
    createdAt: "2024-01-01T08:00:00Z",
    changeHistory: [],
    status: "Approved",
  },
  {
    id: "subst_003",
    identifier: "SS-GRN-01A",
    shortDescription: "Granulation Sub-Station A",
    description: "Wet granulation impeller sub-station",
    level: "3",
    inventoryNumber: "INV-SS-003",
    manufacturer: "GEA Pharma Systems",
    externalId: "SS003",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "BC-SS-003",
    barcodeEnabled: false,
    entityType: "SubStation",
    parentId: "sta4",
    automationServerNameDefault: "",
    automationServerName: "",
    dataOpsPath: "/pharma/coating/wc002/vessel-a/ss-a",
    historianProvider: "",
    historianAccessServerDefault: "",
    historianAccessServer: "",
    historianServerDefault: "",
    historianServer: "",
    createdAt: "2024-01-01T08:00:00Z",
    changeHistory: [],
    status: "Approved",
  },
];
