// Shared Equipment Data — PharmaExec MES
// Extracted from DataManager.tsx so BatchRecords and other modules can import
// equipment master data without circular dependencies.

import type {
  CleaningLevel,
  CleaningLogEntry,
  CleaningRule,
  ComparisonType,
  EquipmentType,
  GmpStatus,
  HealthStatus,
  MaintenanceStatus,
} from "./gmpValidation";

export type EntityType =
  | "WorkCenter"
  | "Room"
  | "Station"
  | "SubStation"
  | "EquipmentClass"
  | "EquipmentEntity"
  | "PropertyType"
  | "ProductMaster";

export interface ChangeEntry {
  timestamp: string;
  field: string;
  oldValue: string;
  newValue: string;
  changedBy: string;
  action?: "Create" | "Update" | "Delete";
  reason?: string;
}

export interface EquipmentNode {
  id: string;
  identifier: string;
  shortDescription: string;
  description: string;
  level: string;
  inventoryNumber: string;
  manufacturer: string;
  externalId: string;
  serialNumber: string;
  manufacturingDate: string;
  disposed: boolean;
  barcode: string;
  barcodeEnabled: boolean;
  entityType: EntityType;
  parentId: string | null;
  automationServerNameDefault: string;
  automationServerName: string;
  dataOpsPath: string;
  historianProvider: string;
  historianAccessServerDefault: string;
  historianAccessServer: string;
  historianServerDefault: string;
  historianServer: string;
  createdAt: string;
  changeHistory: ChangeEntry[];
  // GMP fields
  status?: GmpStatus;
  maintenance_status?: MaintenanceStatus;
  health_status?: HealthStatus;
  last_maintenance_date?: string;
  pm_due_date?: string;
  cleaningRules?: CleaningRule[];
  cleaningLog?: CleaningLogEntry | null;
  // PropertyType capability fields
  min_value?: string;
  max_value?: string;
  required_min?: string;
  required_max?: string;
  comparison_type?: ComparisonType | "";
  // Change Control fields
  versionNumber?: number;
  originalId?: string | null;
  revisedById?: string | null;
  changeControlReason?: string;
  // Lifecycle & Audit fields (added for MES refactor)
  createdBy?: string; // default 'System'
  updatedAt?: string; // ISO string
  isUsedInBatch?: boolean; // default false — locks Edit/Delete when true
  // Advanced Equipment Type & Hierarchy (pharma execution logic)
  equipmentType?: EquipmentType; // Fixed | Moveable
  roomId?: string; // linked Room id
  stationId?: string; // linked Station id
  subStationId?: string; // linked Sub-Station id
  // Advanced Cleaning fields
  cleaningStatus?: "Clean" | "Due" | "Expired";
  lastCleanedAt?: string; // ISO date string
  cleaningValidTill?: string; // ISO date string
  lastProductUsed?: string; // productCode
  cleaningReason?: string; // required for Fixed equipment
  currentCampaignBatches?: number; // batches completed in current campaign
}

export const INITIAL_DATA: EquipmentNode[] = [
  {
    id: "wc1",
    identifier: "WC-COAT-001",
    shortDescription: "W&C Coater",
    description: "Coating Unit Work Center — primary film-coating line",
    level: "1",
    inventoryNumber: "INV-2021-0441",
    manufacturer: "Pharma Machines Ltd",
    externalId: "WC001",
    serialNumber: "PML-2021-C001",
    manufacturingDate: "2021-03-15",
    disposed: false,
    barcode: "BC-WC-001",
    barcodeEnabled: true,
    entityType: "WorkCenter",
    parentId: null,
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "AIS-COAT-01",
    dataOpsPath: "/pharma/coating/wc001",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "PI-COAT-01",
    historianServerDefault: "PIServer1",
    historianServer: "PI-MAIN",
    createdAt: "2024-01-10T08:00:00Z",
    changeHistory: [
      {
        timestamp: "2024-06-12T14:32:00Z",
        field: "automationServerName",
        oldValue: "AIS-OLD",
        newValue: "AIS-COAT-01",
        changedBy: "Dr. Sarah Chen",
      },
    ],
    status: "Approved",
  },
  {
    id: "wc2",
    identifier: "WC-COAT-002",
    shortDescription: "W&C Coater-A",
    description: "Coating Unit Work Center — automated secondary line",
    level: "1",
    inventoryNumber: "INV-2022-0552",
    manufacturer: "Pharma Machines Ltd",
    externalId: "WC002",
    serialNumber: "PML-2022-C002",
    manufacturingDate: "2022-07-20",
    disposed: false,
    barcode: "BC-WC-002",
    barcodeEnabled: true,
    entityType: "WorkCenter",
    parentId: null,
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "AIS-COAT-02",
    dataOpsPath: "/pharma/coating/wc002",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "PI-COAT-02",
    historianServerDefault: "PIServer1",
    historianServer: "PI-MAIN",
    createdAt: "2024-01-10T08:30:00Z",
    changeHistory: [],
    status: "Draft",
  },
  {
    id: "sta1",
    identifier: "STA-FEED-001",
    shortDescription: "Sta Feeder",
    description: "Coating Unit Feeder Station",
    level: "2",
    inventoryNumber: "INV-2021-0442",
    manufacturer: "Fluid Air Inc",
    externalId: "STA001",
    serialNumber: "FAI-2021-F001",
    manufacturingDate: "2021-04-10",
    disposed: false,
    barcode: "BC-STA-001",
    barcodeEnabled: true,
    entityType: "Station",
    parentId: "wc1",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/coating/wc001/feeder",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-11T09:00:00Z",
    changeHistory: [],
    status: "Approved",
  },
  {
    id: "sta2",
    identifier: "STA-FEED-002",
    shortDescription: "Sta Feeder-A",
    description: "Coating Unit Feeder Duplicate Station",
    level: "2",
    inventoryNumber: "INV-2021-0443",
    manufacturer: "Fluid Air Inc",
    externalId: "STA002",
    serialNumber: "FAI-2021-F002",
    manufacturingDate: "2021-04-12",
    disposed: false,
    barcode: "BC-STA-002",
    barcodeEnabled: true,
    entityType: "Station",
    parentId: "wc1",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "AIS-FEED-02",
    dataOpsPath: "/pharma/coating/wc001/feeder-a",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-11T09:15:00Z",
    changeHistory: [],
    status: "Draft",
  },
  {
    id: "sta3",
    identifier: "STA-VESS-001",
    shortDescription: "Sta Vessel",
    description: "Coating Unit Vessel Station",
    level: "2",
    inventoryNumber: "INV-2021-0444",
    manufacturer: "Pharma Machines Ltd",
    externalId: "STA003",
    serialNumber: "PML-2021-V001",
    manufacturingDate: "2021-04-15",
    disposed: false,
    barcode: "BC-STA-003",
    barcodeEnabled: false,
    entityType: "Station",
    parentId: "wc1",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/coating/wc001/vessel",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-11T09:30:00Z",
    changeHistory: [],
    status: "Approved",
  },
  {
    id: "sta4",
    identifier: "STA-VESS-002",
    shortDescription: "Sta Vessel-A",
    description: "Coating Unit Vessel Automated Station",
    level: "2",
    inventoryNumber: "INV-2022-0553",
    manufacturer: "Pharma Machines Ltd",
    externalId: "STA004",
    serialNumber: "PML-2022-V002",
    manufacturingDate: "2022-08-01",
    disposed: false,
    barcode: "BC-STA-004",
    barcodeEnabled: true,
    entityType: "Station",
    parentId: "wc2",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "AIS-VESS-02",
    dataOpsPath: "/pharma/coating/wc002/vessel-a",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "PI-VESS-02",
    historianServerDefault: "PIServer1",
    historianServer: "PI-MAIN",
    createdAt: "2024-01-11T10:00:00Z",
    changeHistory: [],
    status: "Approved",
  },
  {
    id: "ec1",
    identifier: "EC-COAT-001",
    shortDescription: "Coaters",
    description: "Non-automated coating equipment class",
    level: "1",
    inventoryNumber: "INV-CLASS-001",
    manufacturer: "Pharma Machines Ltd",
    externalId: "EC001",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "",
    barcodeEnabled: false,
    entityType: "EquipmentClass",
    parentId: null,
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/classes/coaters",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-05T07:00:00Z",
    changeHistory: [],
    status: "Approved",
    maintenance_status: "Active",
    health_status: "Good",
    pm_due_date: "2026-06-01",
    cleaningRules: [],
    cleaningLog: null,
  },
  {
    id: "ec2",
    identifier: "EC-COAT-002",
    shortDescription: "Coaters-A",
    description: "Automated coating equipment class",
    level: "1",
    inventoryNumber: "INV-CLASS-002",
    manufacturer: "Pharma Machines Ltd",
    externalId: "EC002",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "",
    barcodeEnabled: false,
    entityType: "EquipmentClass",
    parentId: null,
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "AIS-CLASS-02",
    dataOpsPath: "/pharma/classes/coaters-a",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-05T07:30:00Z",
    changeHistory: [],
    status: "Approved",
    maintenance_status: "Active",
    health_status: "Good",
    pm_due_date: "2026-07-15",
    cleaningRules: [],
    cleaningLog: null,
  },
  // ee1: Executed + isUsedInBatch — terminal lock demo
  {
    id: "ee1",
    identifier: "EE-COAT-S",
    shortDescription: "Coater_S",
    description:
      "Small non-automated coating unit — currently in active batch B-2026-001 (Amoxicillin)",
    level: "2",
    inventoryNumber: "INV-2020-0310",
    manufacturer: "Pharma Machines Ltd",
    externalId: "EE001",
    serialNumber: "PML-2020-CS01",
    manufacturingDate: "2020-05-20",
    disposed: false,
    barcode: "BC-EE-001",
    barcodeEnabled: true,
    entityType: "EquipmentEntity",
    parentId: "ec1",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/equipment/coater-s",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-12T08:00:00Z",
    createdBy: "Dr. Sarah Chen",
    updatedAt: "2026-04-01T10:00:00Z",
    changeHistory: [
      {
        timestamp: "2026-04-01T10:00:00Z",
        field: "status",
        oldValue: "Approved",
        newValue: "Executed",
        changedBy: "Dr. Sarah Chen",
        action: "Update",
        reason: "Batch Execution B-2026-001 confirmed",
      },
    ],
    status: "Executed",
    isUsedInBatch: true,
    maintenance_status: "Active",
    health_status: "Good",
    last_maintenance_date: "2025-12-01",
    pm_due_date: "2026-06-01",
    cleaningRules: [],
    cleaningLog: {
      lastProduct: "Amoxicillin 250mg",
      lastCleanedDate: "2026-03-20",
      cleaningLevel: "Major",
      cleaningReason: "Product changeover - end of campaign",
    },
    equipmentType: "Fixed",
    roomId: "room_001",
    stationId: "sta3",
    subStationId: "subst_001",
    cleaningStatus: "Clean",
    lastCleanedAt: "2026-03-20T08:00:00Z",
    cleaningValidTill: "2026-04-20T08:00:00Z",
    lastProductUsed: "PRD-AMX-001",
    cleaningReason: "Product changeover - end of Amoxicillin campaign",
    currentCampaignBatches: 5,
  },
  // ee2: Draft, Active, Good, PM Due Soon — yellow
  {
    id: "ee2",
    identifier: "EE-COAT-M",
    shortDescription: "Coater_M",
    description: "Medium non-automated coating unit",
    level: "2",
    inventoryNumber: "INV-2020-0311",
    manufacturer: "Pharma Machines Ltd",
    externalId: "EE002",
    serialNumber: "PML-2020-CM01",
    manufacturingDate: "2020-06-10",
    disposed: false,
    barcode: "BC-EE-002",
    barcodeEnabled: true,
    entityType: "EquipmentEntity",
    parentId: "ec1",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/equipment/coater-m",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-12T08:15:00Z",
    changeHistory: [],
    status: "Draft",
    maintenance_status: "Active",
    health_status: "Good",
    last_maintenance_date: "2025-11-15",
    pm_due_date: "2026-04-09",
    cleaningRules: [],
    cleaningLog: null,
  },
  // ee3: Approved, Under Maintenance, Bad, PM Overdue — red
  {
    id: "ee3",
    identifier: "EE-COAT-N",
    shortDescription: "Coater_N",
    description: "Nano non-automated coating unit",
    level: "2",
    inventoryNumber: "INV-2021-0315",
    manufacturer: "Fluid Air Inc",
    externalId: "EE003",
    serialNumber: "FAI-2021-CN01",
    manufacturingDate: "2021-01-25",
    disposed: false,
    barcode: "BC-EE-003",
    barcodeEnabled: false,
    entityType: "EquipmentEntity",
    parentId: "ec1",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/equipment/coater-n",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-12T08:30:00Z",
    changeHistory: [],
    status: "Approved",
    maintenance_status: "Under Maintenance",
    health_status: "Bad",
    last_maintenance_date: "2025-09-10",
    pm_due_date: "2026-03-15",
    cleaningRules: [],
    cleaningLog: null,
    equipmentType: "Moveable",
    roomId: "room_002",
    stationId: "sta3",
    subStationId: "subst_002",
    cleaningStatus: "Expired",
    lastCleanedAt: "2026-01-01T08:00:00Z",
    cleaningValidTill: "2026-01-03T08:00:00Z",
    lastProductUsed: "PRD-OMP-003",
    currentCampaignBatches: 4,
  },
  // ee4: Approved, Active, Good, PM OK, cleaning Required — red
  {
    id: "ee4",
    identifier: "EE-COAT-AT",
    shortDescription: "Coater_At",
    description: "Automated tablet coating unit",
    level: "2",
    inventoryNumber: "INV-2022-0560",
    manufacturer: "GEA Pharma Systems",
    externalId: "EE004",
    serialNumber: "GEA-2022-AT01",
    manufacturingDate: "2022-03-14",
    disposed: false,
    barcode: "BC-EE-004",
    barcodeEnabled: true,
    entityType: "EquipmentEntity",
    parentId: "ec2",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "AIS-EE-04",
    dataOpsPath: "/pharma/equipment/coater-at",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "PI-EE-04",
    historianServerDefault: "PIServer1",
    historianServer: "PI-MAIN",
    createdAt: "2024-01-12T09:00:00Z",
    changeHistory: [],
    status: "Approved",
    isUsedInBatch: true,
    createdBy: "Dr. Sarah Chen",
    updatedAt: "2026-03-28T11:00:00Z",
    maintenance_status: "Active",
    health_status: "Good",
    last_maintenance_date: "2026-01-20",
    pm_due_date: "2026-07-20",
    cleaningRules: [
      {
        id: "cr1",
        previousProduct: "Amoxicillin 500mg",
        nextProduct: "Metformin 500mg",
        requiredCleaningLevel: "Major",
      },
      {
        id: "cr2",
        previousProduct: "Ciprofloxacin 500mg",
        nextProduct: "Paracetamol 500mg",
        requiredCleaningLevel: "Minor",
      },
    ],
    cleaningLog: {
      lastProduct: "Amoxicillin 500mg",
      lastCleanedDate: "2026-03-28",
      cleaningLevel: "Minor",
    },
    equipmentType: "Fixed",
    roomId: "room_001",
    stationId: "sta4",
    subStationId: "subst_003",
    cleaningStatus: "Due",
    lastCleanedAt: "2026-03-28T07:00:00Z",
    cleaningValidTill: "2026-04-06T07:00:00Z",
    lastProductUsed: "PRD-AMX-001",
    cleaningReason: "Routine inter-batch cleaning",
    currentCampaignBatches: 3,
  },
  // ee5: Draft, Active, Good, PM OK, cleaning OK — green
  {
    id: "ee5",
    identifier: "EE-COAT-AM",
    shortDescription: "Coater_AM",
    description: "Automated membrane coating unit",
    level: "2",
    inventoryNumber: "INV-2022-0561",
    manufacturer: "GEA Pharma Systems",
    externalId: "EE005",
    serialNumber: "GEA-2022-AM01",
    manufacturingDate: "2022-04-08",
    disposed: false,
    barcode: "BC-EE-005",
    barcodeEnabled: true,
    entityType: "EquipmentEntity",
    parentId: "ec2",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "AIS-EE-05",
    dataOpsPath: "/pharma/equipment/coater-am",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "PI-EE-05",
    historianServerDefault: "PIServer1",
    historianServer: "PI-MAIN",
    createdAt: "2024-01-12T09:15:00Z",
    changeHistory: [],
    status: "Executed",
    isUsedInBatch: false,
    createdBy: "Dr. Sarah Chen",
    updatedAt: "2026-03-15T09:00:00Z",
    maintenance_status: "Active",
    health_status: "Good",
    last_maintenance_date: "2026-02-10",
    pm_due_date: "2026-08-10",
    cleaningRules: [],
    cleaningLog: {
      lastProduct: "Paracetamol 500mg",
      lastCleanedDate: "2026-03-30",
      cleaningLevel: "Major",
      cleaningReason: "Major cleaning after Paracetamol campaign",
    },
    equipmentType: "Moveable",
    roomId: "room_002",
    stationId: "sta4",
    cleaningStatus: "Clean",
    lastCleanedAt: "2026-03-30T09:00:00Z",
    cleaningValidTill: "2026-04-30T09:00:00Z",
    lastProductUsed: "PRD-MET-002",
    currentCampaignBatches: 2,
  },
  // ee6: Approved, Active, Bad, PM Overdue — red
  {
    id: "ee6",
    identifier: "EE-COAT-AK",
    shortDescription: "Coater_Ak",
    description: "Automated kinetic coating unit",
    level: "2",
    inventoryNumber: "INV-2023-0600",
    manufacturer: "GEA Pharma Systems",
    externalId: "EE006",
    serialNumber: "GEA-2023-AK01",
    manufacturingDate: "2023-01-30",
    disposed: false,
    barcode: "BC-EE-006",
    barcodeEnabled: true,
    entityType: "EquipmentEntity",
    parentId: "ec2",
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "AIS-EE-06",
    dataOpsPath: "/pharma/equipment/coater-ak",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "PI-EE-06",
    historianServerDefault: "PIServer1",
    historianServer: "PI-MAIN",
    createdAt: "2024-01-12T09:30:00Z",
    changeHistory: [],
    status: "Approved",
    maintenance_status: "Active",
    health_status: "Bad",
    last_maintenance_date: "2025-08-01",
    pm_due_date: "2026-02-28",
    cleaningRules: [],
    cleaningLog: null,
    equipmentType: "Fixed",
    roomId: "room_002",
    stationId: "sta4",
    cleaningStatus: "Expired",
    lastCleanedAt: "2026-02-01T08:00:00Z",
    cleaningValidTill: "2026-02-03T08:00:00Z",
    lastProductUsed: "PRD-CIP-005",
    currentCampaignBatches: 3,
  },
  {
    id: "pt1",
    identifier: "PT-BATCHID",
    shortDescription: "Batch ID",
    description: "Unique batch identifier property type",
    level: "1",
    inventoryNumber: "",
    manufacturer: "",
    externalId: "PT001",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "",
    barcodeEnabled: false,
    entityType: "PropertyType",
    parentId: null,
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/properties/batch-id",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-08T10:00:00Z",
    changeHistory: [],
    status: "Approved",
    min_value: "",
    max_value: "",
    required_min: "",
    required_max: "",
    comparison_type: "",
  },
  {
    id: "pt2",
    identifier: "PT-COATPREP",
    shortDescription: "Coater Prepared",
    description: "Flag indicating coater has been prepared for batch",
    level: "1",
    inventoryNumber: "",
    manufacturer: "",
    externalId: "PT002",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "",
    barcodeEnabled: false,
    entityType: "PropertyType",
    parentId: null,
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/properties/coater-prepared",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-08T10:15:00Z",
    changeHistory: [],
    status: "Approved",
    min_value: "",
    max_value: "",
    required_min: "",
    required_max: "",
    comparison_type: "",
  },
  {
    id: "pt3",
    identifier: "PT-DRUMSIZE",
    shortDescription: "Drum Size",
    description: "Coating drum volume in litres",
    level: "1",
    inventoryNumber: "",
    manufacturer: "",
    externalId: "PT003",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "",
    barcodeEnabled: false,
    entityType: "PropertyType",
    parentId: null,
    automationServerNameDefault: "AutomationIntegrationServer1",
    automationServerName: "",
    dataOpsPath: "/pharma/properties/drum-size",
    historianProvider: "PIConnector",
    historianAccessServerDefault: "PIAccessServer1",
    historianAccessServer: "",
    historianServerDefault: "PIServer1",
    historianServer: "",
    createdAt: "2024-01-08T10:30:00Z",
    changeHistory: [],
    status: "Draft",
    min_value: "10",
    max_value: "200",
    required_min: "50",
    required_max: "150",
    comparison_type: "WITHIN_RANGE",
  },
  // Room nodes — top of location hierarchy
  {
    id: "room_001",
    identifier: "RM-MFG-01",
    shortDescription: "Manufacturing Room A",
    description: "Primary solid dosage manufacturing area — ISO 8 clean room",
    level: "0",
    inventoryNumber: "INV-RM-001",
    manufacturer: "Facility",
    externalId: "RM001",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "BC-RM-001",
    barcodeEnabled: false,
    entityType: "Room",
    parentId: null,
    automationServerNameDefault: "",
    automationServerName: "",
    dataOpsPath: "/pharma/rooms/mfg-a",
    historianProvider: "",
    historianAccessServerDefault: "",
    historianAccessServer: "",
    historianServerDefault: "",
    historianServer: "",
    createdAt: "2024-01-01T08:00:00Z",
    changeHistory: [],
    status: "Approved",
  },
  {
    id: "room_002",
    identifier: "RM-MFG-02",
    shortDescription: "Manufacturing Room B",
    description: "Secondary coating and granulation area — ISO 7 clean room",
    level: "0",
    inventoryNumber: "INV-RM-002",
    manufacturer: "Facility",
    externalId: "RM002",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "BC-RM-002",
    barcodeEnabled: false,
    entityType: "Room",
    parentId: null,
    automationServerNameDefault: "",
    automationServerName: "",
    dataOpsPath: "/pharma/rooms/mfg-b",
    historianProvider: "",
    historianAccessServerDefault: "",
    historianAccessServer: "",
    historianServerDefault: "",
    historianServer: "",
    createdAt: "2024-01-01T08:00:00Z",
    changeHistory: [],
    status: "Approved",
  },
  // SubStation nodes — between Station and Equipment
  {
    id: "subst_001",
    identifier: "SS-COAT-01A",
    shortDescription: "Coating Sub-Station A",
    description: "Sub-station for drum loading and spray system",
    level: "3",
    inventoryNumber: "INV-SS-001",
    manufacturer: "Pharma Machines Ltd",
    externalId: "SS001",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "BC-SS-001",
    barcodeEnabled: false,
    entityType: "SubStation",
    parentId: "sta3",
    automationServerNameDefault: "",
    automationServerName: "",
    dataOpsPath: "/pharma/coating/wc001/vessel/ss-a",
    historianProvider: "",
    historianAccessServerDefault: "",
    historianAccessServer: "",
    historianServerDefault: "",
    historianServer: "",
    createdAt: "2024-01-01T08:00:00Z",
    changeHistory: [],
    status: "Approved",
  },
  {
    id: "subst_002",
    identifier: "SS-COAT-01B",
    shortDescription: "Coating Sub-Station B",
    description: "Sub-station for air handling and exhaust",
    level: "3",
    inventoryNumber: "INV-SS-002",
    manufacturer: "Pharma Machines Ltd",
    externalId: "SS002",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "BC-SS-002",
    barcodeEnabled: false,
    entityType: "SubStation",
    parentId: "sta3",
    automationServerNameDefault: "",
    automationServerName: "",
    dataOpsPath: "/pharma/coating/wc001/vessel/ss-b",
    historianProvider: "",
    historianAccessServerDefault: "",
    historianAccessServer: "",
    historianServerDefault: "",
    historianServer: "",
    createdAt: "2024-01-01T08:00:00Z",
    changeHistory: [],
    status: "Approved",
  },
  {
    id: "subst_003",
    identifier: "SS-GRN-01A",
    shortDescription: "Granulation Sub-Station A",
    description: "Wet granulation impeller sub-station",
    level: "3",
    inventoryNumber: "INV-SS-003",
    manufacturer: "GEA Pharma Systems",
    externalId: "SS003",
    serialNumber: "",
    manufacturingDate: "",
    disposed: false,
    barcode: "BC-SS-003",
    barcodeEnabled: false,
    entityType: "SubStation",
    parentId: "sta4",
    automationServerNameDefault: "",
    automationServerName: "",
    dataOpsPath: "/pharma/coating/wc002/vessel-a/ss-a",
    historianProvider: "",
    historianAccessServerDefault: "",
    historianAccessServer: "",
    historianServerDefault: "",
    historianServer: "",
    createdAt: "2024-01-01T08:00:00Z",
    changeHistory: [],
    status: "Approved",
  },
];
