/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PersonnelRole = IDL.Variant({
  'admin' : IDL.Null,
  'productionManager' : IDL.Null,
  'operator' : IDL.Null,
  'qaInspector' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BatchStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'inProgress' : IDL.Null,
  'onHold' : IDL.Null,
});
export const BatchRecord = IDL.Record({
  'startTime' : IDL.Int,
  'status' : BatchStatus,
  'unit' : IDL.Text,
  'productName' : IDL.Text,
  'operatorId' : IDL.Principal,
  'notes' : IDL.Text,
  'batchId' : IDL.Text,
  'currentStage' : IDL.Text,
  'batchSize' : IDL.Float64,
});
export const DeviationStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'underInvestigation' : IDL.Null,
});
export const DeviationSeverity = IDL.Variant({
  'major' : IDL.Null,
  'minor' : IDL.Null,
  'critical' : IDL.Null,
});
export const Deviation = IDL.Record({
  'title' : IDL.Text,
  'capaDescription' : IDL.Text,
  'reportedDate' : IDL.Int,
  'description' : IDL.Text,
  'deviationStatus' : DeviationStatus,
  'reportedBy' : IDL.Principal,
  'batchRecordId' : IDL.Text,
  'severity' : DeviationSeverity,
  'deviationId' : IDL.Text,
});
export const EquipmentStatus = IDL.Variant({
  'cleaning' : IDL.Null,
  'available' : IDL.Null,
  'maintenance' : IDL.Null,
  'inUse' : IDL.Null,
});
export const Equipment = IDL.Record({
  'status' : EquipmentStatus,
  'lastMaintenance' : IDL.Int,
  'name' : IDL.Text,
  'equipmentType' : IDL.Text,
  'notes' : IDL.Text,
  'equipmentId' : IDL.Text,
  'location' : IDL.Text,
});
export const MaterialStatus = IDL.Variant({
  'released' : IDL.Null,
  'consumed' : IDL.Null,
  'rejected' : IDL.Null,
  'quarantine' : IDL.Null,
});
export const Material = IDL.Record({
  'expiryDate' : IDL.Int,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'materialId' : IDL.Text,
  'lotNumber' : IDL.Text,
  'materialStatus' : MaterialStatus,
  'quantity' : IDL.Float64,
  'storageLocation' : IDL.Text,
});
export const PersonnelPure = IDL.Record({
  'name' : IDL.Text,
  'role' : PersonnelRole,
  'isActive' : IDL.Bool,
  'certifications' : IDL.Vec(IDL.Text),
  'principalId' : IDL.Principal,
});
export const WorkOrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'open' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const WorkOrder = IDL.Record({
  'status' : WorkOrderStatus,
  'scheduledStart' : IDL.Int,
  'assignedTo' : IDL.Principal,
  'description' : IDL.Text,
  'workOrderId' : IDL.Text,
  'batchRecordId' : IDL.Text,
  'priority' : IDL.Text,
});
export const EntityType = IDL.Variant({
  'equipment' : IDL.Null,
  'deviation' : IDL.Null,
  'personnel' : IDL.Null,
  'workOrder' : IDL.Null,
  'material' : IDL.Null,
  'batchRecord' : IDL.Null,
});
export const AuditEvent = IDL.Record({
  'eventId' : IDL.Text,
  'action' : IDL.Text,
  'userId' : IDL.Principal,
  'entityId' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'entityType' : EntityType,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : PersonnelRole,
  'isActive' : IDL.Bool,
  'certifications' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEquipment' : IDL.Func(
      [
        IDL.Record({
          'name' : IDL.Text,
          'equipmentType' : IDL.Text,
          'notes' : IDL.Text,
          'location' : IDL.Text,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'addMaterial' : IDL.Func(
      [
        IDL.Record({
          'expiryDate' : IDL.Int,
          'name' : IDL.Text,
          'unit' : IDL.Text,
          'lotNumber' : IDL.Text,
          'quantity' : IDL.Float64,
          'storageLocation' : IDL.Text,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'addPersonnel' : IDL.Func(
      [
        IDL.Record({
          'name' : IDL.Text,
          'role' : PersonnelRole,
          'certifications' : IDL.Vec(IDL.Text),
          'principalId' : IDL.Principal,
        }),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRoleToUser' : IDL.Func([IDL.Principal, UserRole], [], []),
  'closeDeviation' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'consumeMaterial' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'createBatchRecord' : IDL.Func(
      [
        IDL.Record({
          'unit' : IDL.Text,
          'productName' : IDL.Text,
          'operatorId' : IDL.Principal,
          'notes' : IDL.Text,
          'currentStage' : IDL.Text,
          'batchSize' : IDL.Float64,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'createWorkOrder' : IDL.Func(
      [
        IDL.Record({
          'scheduledStart' : IDL.Int,
          'assignedTo' : IDL.Principal,
          'description' : IDL.Text,
          'batchRecordId' : IDL.Text,
          'priority' : IDL.Text,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'deactivatePersonnel' : IDL.Func([IDL.Principal], [], []),
  'getAllBatchRecords' : IDL.Func([], [IDL.Vec(BatchRecord)], ['query']),
  'getAllDeviations' : IDL.Func([], [IDL.Vec(Deviation)], ['query']),
  'getAllEquipment' : IDL.Func([], [IDL.Vec(Equipment)], ['query']),
  'getAllMaterials' : IDL.Func([], [IDL.Vec(Material)], ['query']),
  'getAllPersonnel' : IDL.Func([], [IDL.Vec(PersonnelPure)], ['query']),
  'getAllWorkOrders' : IDL.Func([], [IDL.Vec(WorkOrder)], ['query']),
  'getAuditTrailForEntity' : IDL.Func(
      [EntityType, IDL.Text],
      [IDL.Vec(AuditEvent)],
      ['query'],
    ),
  'getAuditTrailForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AuditEvent)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkOrder' : IDL.Func([IDL.Text], [WorkOrder], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reportDeviation' : IDL.Func(
      [
        IDL.Record({
          'title' : IDL.Text,
          'description' : IDL.Text,
          'batchRecordId' : IDL.Text,
          'severity' : DeviationSeverity,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBatchStatus' : IDL.Func([IDL.Text, BatchStatus], [], []),
  'updateEquipmentStatus' : IDL.Func([IDL.Text, EquipmentStatus], [], []),
  'updateWorkOrderStatus' : IDL.Func([IDL.Text, WorkOrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PersonnelRole = IDL.Variant({
    'admin' : IDL.Null,
    'productionManager' : IDL.Null,
    'operator' : IDL.Null,
    'qaInspector' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BatchStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'inProgress' : IDL.Null,
    'onHold' : IDL.Null,
  });
  const BatchRecord = IDL.Record({
    'startTime' : IDL.Int,
    'status' : BatchStatus,
    'unit' : IDL.Text,
    'productName' : IDL.Text,
    'operatorId' : IDL.Principal,
    'notes' : IDL.Text,
    'batchId' : IDL.Text,
    'currentStage' : IDL.Text,
    'batchSize' : IDL.Float64,
  });
  const DeviationStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'underInvestigation' : IDL.Null,
  });
  const DeviationSeverity = IDL.Variant({
    'major' : IDL.Null,
    'minor' : IDL.Null,
    'critical' : IDL.Null,
  });
  const Deviation = IDL.Record({
    'title' : IDL.Text,
    'capaDescription' : IDL.Text,
    'reportedDate' : IDL.Int,
    'description' : IDL.Text,
    'deviationStatus' : DeviationStatus,
    'reportedBy' : IDL.Principal,
    'batchRecordId' : IDL.Text,
    'severity' : DeviationSeverity,
    'deviationId' : IDL.Text,
  });
  const EquipmentStatus = IDL.Variant({
    'cleaning' : IDL.Null,
    'available' : IDL.Null,
    'maintenance' : IDL.Null,
    'inUse' : IDL.Null,
  });
  const Equipment = IDL.Record({
    'status' : EquipmentStatus,
    'lastMaintenance' : IDL.Int,
    'name' : IDL.Text,
    'equipmentType' : IDL.Text,
    'notes' : IDL.Text,
    'equipmentId' : IDL.Text,
    'location' : IDL.Text,
  });
  const MaterialStatus = IDL.Variant({
    'released' : IDL.Null,
    'consumed' : IDL.Null,
    'rejected' : IDL.Null,
    'quarantine' : IDL.Null,
  });
  const Material = IDL.Record({
    'expiryDate' : IDL.Int,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'materialId' : IDL.Text,
    'lotNumber' : IDL.Text,
    'materialStatus' : MaterialStatus,
    'quantity' : IDL.Float64,
    'storageLocation' : IDL.Text,
  });
  const PersonnelPure = IDL.Record({
    'name' : IDL.Text,
    'role' : PersonnelRole,
    'isActive' : IDL.Bool,
    'certifications' : IDL.Vec(IDL.Text),
    'principalId' : IDL.Principal,
  });
  const WorkOrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'open' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const WorkOrder = IDL.Record({
    'status' : WorkOrderStatus,
    'scheduledStart' : IDL.Int,
    'assignedTo' : IDL.Principal,
    'description' : IDL.Text,
    'workOrderId' : IDL.Text,
    'batchRecordId' : IDL.Text,
    'priority' : IDL.Text,
  });
  const EntityType = IDL.Variant({
    'equipment' : IDL.Null,
    'deviation' : IDL.Null,
    'personnel' : IDL.Null,
    'workOrder' : IDL.Null,
    'material' : IDL.Null,
    'batchRecord' : IDL.Null,
  });
  const AuditEvent = IDL.Record({
    'eventId' : IDL.Text,
    'action' : IDL.Text,
    'userId' : IDL.Principal,
    'entityId' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'entityType' : EntityType,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : PersonnelRole,
    'isActive' : IDL.Bool,
    'certifications' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEquipment' : IDL.Func(
        [
          IDL.Record({
            'name' : IDL.Text,
            'equipmentType' : IDL.Text,
            'notes' : IDL.Text,
            'location' : IDL.Text,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'addMaterial' : IDL.Func(
        [
          IDL.Record({
            'expiryDate' : IDL.Int,
            'name' : IDL.Text,
            'unit' : IDL.Text,
            'lotNumber' : IDL.Text,
            'quantity' : IDL.Float64,
            'storageLocation' : IDL.Text,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'addPersonnel' : IDL.Func(
        [
          IDL.Record({
            'name' : IDL.Text,
            'role' : PersonnelRole,
            'certifications' : IDL.Vec(IDL.Text),
            'principalId' : IDL.Principal,
          }),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRoleToUser' : IDL.Func([IDL.Principal, UserRole], [], []),
    'closeDeviation' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'consumeMaterial' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'createBatchRecord' : IDL.Func(
        [
          IDL.Record({
            'unit' : IDL.Text,
            'productName' : IDL.Text,
            'operatorId' : IDL.Principal,
            'notes' : IDL.Text,
            'currentStage' : IDL.Text,
            'batchSize' : IDL.Float64,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'createWorkOrder' : IDL.Func(
        [
          IDL.Record({
            'scheduledStart' : IDL.Int,
            'assignedTo' : IDL.Principal,
            'description' : IDL.Text,
            'batchRecordId' : IDL.Text,
            'priority' : IDL.Text,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'deactivatePersonnel' : IDL.Func([IDL.Principal], [], []),
    'getAllBatchRecords' : IDL.Func([], [IDL.Vec(BatchRecord)], ['query']),
    'getAllDeviations' : IDL.Func([], [IDL.Vec(Deviation)], ['query']),
    'getAllEquipment' : IDL.Func([], [IDL.Vec(Equipment)], ['query']),
    'getAllMaterials' : IDL.Func([], [IDL.Vec(Material)], ['query']),
    'getAllPersonnel' : IDL.Func([], [IDL.Vec(PersonnelPure)], ['query']),
    'getAllWorkOrders' : IDL.Func([], [IDL.Vec(WorkOrder)], ['query']),
    'getAuditTrailForEntity' : IDL.Func(
        [EntityType, IDL.Text],
        [IDL.Vec(AuditEvent)],
        ['query'],
      ),
    'getAuditTrailForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AuditEvent)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkOrder' : IDL.Func([IDL.Text], [WorkOrder], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reportDeviation' : IDL.Func(
        [
          IDL.Record({
            'title' : IDL.Text,
            'description' : IDL.Text,
            'batchRecordId' : IDL.Text,
            'severity' : DeviationSeverity,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBatchStatus' : IDL.Func([IDL.Text, BatchStatus], [], []),
    'updateEquipmentStatus' : IDL.Func([IDL.Text, EquipmentStatus], [], []),
    'updateWorkOrderStatus' : IDL.Func([IDL.Text, WorkOrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };