/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditEvent {
  'eventId' : string,
  'action' : string,
  'userId' : Principal,
  'entityId' : string,
  'timestamp' : bigint,
  'details' : string,
  'entityType' : EntityType,
}
export interface BatchRecord {
  'startTime' : bigint,
  'status' : BatchStatus,
  'unit' : string,
  'productName' : string,
  'operatorId' : Principal,
  'notes' : string,
  'batchId' : string,
  'currentStage' : string,
  'batchSize' : number,
}
export type BatchStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'inProgress' : null } |
  { 'onHold' : null };
export interface Deviation {
  'title' : string,
  'capaDescription' : string,
  'reportedDate' : bigint,
  'description' : string,
  'deviationStatus' : DeviationStatus,
  'reportedBy' : Principal,
  'batchRecordId' : string,
  'severity' : DeviationSeverity,
  'deviationId' : string,
}
export type DeviationSeverity = { 'major' : null } |
  { 'minor' : null } |
  { 'critical' : null };
export type DeviationStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'underInvestigation' : null };
export type EntityType = { 'equipment' : null } |
  { 'deviation' : null } |
  { 'personnel' : null } |
  { 'workOrder' : null } |
  { 'material' : null } |
  { 'batchRecord' : null };
export interface Equipment {
  'status' : EquipmentStatus,
  'lastMaintenance' : bigint,
  'name' : string,
  'equipmentType' : string,
  'notes' : string,
  'equipmentId' : string,
  'location' : string,
}
export type EquipmentStatus = { 'cleaning' : null } |
  { 'available' : null } |
  { 'maintenance' : null } |
  { 'inUse' : null };
export interface Material {
  'expiryDate' : bigint,
  'name' : string,
  'unit' : string,
  'materialId' : string,
  'lotNumber' : string,
  'materialStatus' : MaterialStatus,
  'quantity' : number,
  'storageLocation' : string,
}
export type MaterialStatus = { 'released' : null } |
  { 'consumed' : null } |
  { 'rejected' : null } |
  { 'quarantine' : null };
export interface PersonnelPure {
  'name' : string,
  'role' : PersonnelRole,
  'isActive' : boolean,
  'certifications' : Array<string>,
  'principalId' : Principal,
}
export type PersonnelRole = { 'admin' : null } |
  { 'productionManager' : null } |
  { 'operator' : null } |
  { 'qaInspector' : null };
export interface UserProfile {
  'name' : string,
  'role' : PersonnelRole,
  'isActive' : boolean,
  'certifications' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkOrder {
  'status' : WorkOrderStatus,
  'scheduledStart' : bigint,
  'assignedTo' : Principal,
  'description' : string,
  'workOrderId' : string,
  'batchRecordId' : string,
  'priority' : string,
}
export type WorkOrderStatus = { 'cancelled' : null } |
  { 'open' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEquipment' : ActorMethod<
    [
      {
        'name' : string,
        'equipmentType' : string,
        'notes' : string,
        'location' : string,
      },
    ],
    string
  >,
  'addMaterial' : ActorMethod<
    [
      {
        'expiryDate' : bigint,
        'name' : string,
        'unit' : string,
        'lotNumber' : string,
        'quantity' : number,
        'storageLocation' : string,
      },
    ],
    string
  >,
  'addPersonnel' : ActorMethod<
    [
      {
        'name' : string,
        'role' : PersonnelRole,
        'certifications' : Array<string>,
        'principalId' : Principal,
      },
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRoleToUser' : ActorMethod<[Principal, UserRole], undefined>,
  'closeDeviation' : ActorMethod<[string, string], undefined>,
  'consumeMaterial' : ActorMethod<[string, number], undefined>,
  'createBatchRecord' : ActorMethod<
    [
      {
        'unit' : string,
        'productName' : string,
        'operatorId' : Principal,
        'notes' : string,
        'currentStage' : string,
        'batchSize' : number,
      },
    ],
    string
  >,
  'createWorkOrder' : ActorMethod<
    [
      {
        'scheduledStart' : bigint,
        'assignedTo' : Principal,
        'description' : string,
        'batchRecordId' : string,
        'priority' : string,
      },
    ],
    string
  >,
  'deactivatePersonnel' : ActorMethod<[Principal], undefined>,
  'getAllBatchRecords' : ActorMethod<[], Array<BatchRecord>>,
  'getAllDeviations' : ActorMethod<[], Array<Deviation>>,
  'getAllEquipment' : ActorMethod<[], Array<Equipment>>,
  'getAllMaterials' : ActorMethod<[], Array<Material>>,
  'getAllPersonnel' : ActorMethod<[], Array<PersonnelPure>>,
  'getAllWorkOrders' : ActorMethod<[], Array<WorkOrder>>,
  'getAuditTrailForEntity' : ActorMethod<
    [EntityType, string],
    Array<AuditEvent>
  >,
  'getAuditTrailForUser' : ActorMethod<[Principal], Array<AuditEvent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkOrder' : ActorMethod<[string], WorkOrder>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reportDeviation' : ActorMethod<
    [
      {
        'title' : string,
        'description' : string,
        'batchRecordId' : string,
        'severity' : DeviationSeverity,
      },
    ],
    string
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBatchStatus' : ActorMethod<[string, BatchStatus], undefined>,
  'updateEquipmentStatus' : ActorMethod<[string, EquipmentStatus], undefined>,
  'updateWorkOrderStatus' : ActorMethod<[string, WorkOrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];