/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface WorkOrder {
    status: WorkOrderStatus;
    scheduledStart: bigint;
    assignedTo: Principal;
    description: string;
    workOrderId: string;
    batchRecordId: string;
    priority: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Equipment {
    status: EquipmentStatus;
    lastMaintenance: bigint;
    name: string;
    equipmentType: string;
    notes: string;
    equipmentId: string;
    location: string;
}
export interface Deviation {
    title: string;
    capaDescription: string;
    reportedDate: bigint;
    description: string;
    deviationStatus: DeviationStatus;
    reportedBy: Principal;
    batchRecordId: string;
    severity: DeviationSeverity;
    deviationId: string;
}
export interface BatchRecord {
    startTime: bigint;
    status: BatchStatus;
    unit: string;
    productName: string;
    operatorId: Principal;
    notes: string;
    batchId: string;
    currentStage: string;
    batchSize: number;
}
export interface Material {
    expiryDate: bigint;
    name: string;
    unit: string;
    materialId: string;
    lotNumber: string;
    materialStatus: MaterialStatus;
    quantity: number;
    storageLocation: string;
}
export interface AuditEvent {
    eventId: string;
    action: string;
    userId: Principal;
    entityId: string;
    timestamp: bigint;
    details: string;
    entityType: EntityType;
}
export interface UserProfile {
    name: string;
    role: PersonnelRole;
    isActive: boolean;
    certifications: Array<string>;
}
export interface PersonnelPure {
    name: string;
    role: PersonnelRole;
    isActive: boolean;
    certifications: Array<string>;
    principalId: Principal;
}
export enum BatchStatus {
    pending = "pending",
    completed = "completed",
    rejected = "rejected",
    inProgress = "inProgress",
    onHold = "onHold"
}
export enum DeviationSeverity {
    major = "major",
    minor = "minor",
    critical = "critical"
}
export enum DeviationStatus {
    closed = "closed",
    open = "open",
    underInvestigation = "underInvestigation"
}
export enum EntityType {
    equipment = "equipment",
    deviation = "deviation",
    personnel = "personnel",
    workOrder = "workOrder",
    material = "material",
    batchRecord = "batchRecord"
}
export enum EquipmentStatus {
    cleaning = "cleaning",
    available = "available",
    maintenance = "maintenance",
    inUse = "inUse"
}
export enum MaterialStatus {
    released = "released",
    consumed = "consumed",
    rejected = "rejected",
    quarantine = "quarantine"
}
export enum PersonnelRole {
    admin = "admin",
    productionManager = "productionManager",
    operator = "operator",
    qaInspector = "qaInspector"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WorkOrderStatus {
    cancelled = "cancelled",
    open = "open",
    completed = "completed",
    inProgress = "inProgress"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addEquipment(input: {
        name: string;
        equipmentType: string;
        notes: string;
        location: string;
    }): Promise<string>;
    addMaterial(input: {
        expiryDate: bigint;
        name: string;
        unit: string;
        lotNumber: string;
        quantity: number;
        storageLocation: string;
    }): Promise<string>;
    addPersonnel(input: {
        name: string;
        role: PersonnelRole;
        certifications: Array<string>;
        principalId: Principal;
    }): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRoleToUser(user: Principal, role: UserRole): Promise<void>;
    closeDeviation(deviationId: string, capaDescription: string): Promise<void>;
    consumeMaterial(materialId: string, amount: number): Promise<void>;
    createBatchRecord(input: {
        unit: string;
        productName: string;
        operatorId: Principal;
        notes: string;
        currentStage: string;
        batchSize: number;
    }): Promise<string>;
    createWorkOrder(input: {
        scheduledStart: bigint;
        assignedTo: Principal;
        description: string;
        batchRecordId: string;
        priority: string;
    }): Promise<string>;
    deactivatePersonnel(principalId: Principal): Promise<void>;
    getAllBatchRecords(): Promise<Array<BatchRecord>>;
    getAllDeviations(): Promise<Array<Deviation>>;
    getAllEquipment(): Promise<Array<Equipment>>;
    getAllMaterials(): Promise<Array<Material>>;
    getAllPersonnel(): Promise<Array<PersonnelPure>>;
    getAllWorkOrders(): Promise<Array<WorkOrder>>;
    getAuditTrailForEntity(entityType: EntityType, entityId: string): Promise<Array<AuditEvent>>;
    getAuditTrailForUser(userId: Principal): Promise<Array<AuditEvent>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkOrder(workOrderId: string): Promise<WorkOrder>;
    isCallerAdmin(): Promise<boolean>;
    reportDeviation(input: {
        title: string;
        description: string;
        batchRecordId: string;
        severity: DeviationSeverity;
    }): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBatchStatus(batchId: string, status: BatchStatus): Promise<void>;
    updateEquipmentStatus(equipmentId: string, status: EquipmentStatus): Promise<void>;
    updateWorkOrderStatus(workOrderId: string, status: WorkOrderStatus): Promise<void>;
}
import type { AuditEvent as _AuditEvent, BatchRecord as _BatchRecord, BatchStatus as _BatchStatus, Deviation as _Deviation, DeviationSeverity as _DeviationSeverity, DeviationStatus as _DeviationStatus, EntityType as _EntityType, Equipment as _Equipment, EquipmentStatus as _EquipmentStatus, Material as _Material, MaterialStatus as _MaterialStatus, PersonnelPure as _PersonnelPure, PersonnelRole as _PersonnelRole, UserProfile as _UserProfile, UserRole as _UserRole, WorkOrder as _WorkOrder, WorkOrderStatus as _WorkOrderStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addEquipment(arg0: {
        name: string;
        equipmentType: string;
        notes: string;
        location: string;
    }): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addEquipment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEquipment(arg0);
            return result;
        }
    }
    async addMaterial(arg0: {
        expiryDate: bigint;
        name: string;
        unit: string;
        lotNumber: string;
        quantity: number;
        storageLocation: string;
    }): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMaterial(arg0);
            return result;
        }
    }
    async addPersonnel(arg0: {
        name: string;
        role: PersonnelRole;
        certifications: Array<string>;
        principalId: Principal;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPersonnel(to_candid_record_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPersonnel(to_candid_record_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRoleToUser(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRoleToUser(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRoleToUser(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async closeDeviation(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closeDeviation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeDeviation(arg0, arg1);
            return result;
        }
    }
    async consumeMaterial(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.consumeMaterial(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.consumeMaterial(arg0, arg1);
            return result;
        }
    }
    async createBatchRecord(arg0: {
        unit: string;
        productName: string;
        operatorId: Principal;
        notes: string;
        currentStage: string;
        batchSize: number;
    }): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createBatchRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBatchRecord(arg0);
            return result;
        }
    }
    async createWorkOrder(arg0: {
        scheduledStart: bigint;
        assignedTo: Principal;
        description: string;
        batchRecordId: string;
        priority: string;
    }): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkOrder(arg0);
            return result;
        }
    }
    async deactivatePersonnel(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivatePersonnel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivatePersonnel(arg0);
            return result;
        }
    }
    async getAllBatchRecords(): Promise<Array<BatchRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBatchRecords();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBatchRecords();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDeviations(): Promise<Array<Deviation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeviations();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeviations();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEquipment(): Promise<Array<Equipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEquipment();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEquipment();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMaterials(): Promise<Array<Material>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMaterials();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMaterials();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPersonnel(): Promise<Array<PersonnelPure>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPersonnel();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPersonnel();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWorkOrders(): Promise<Array<WorkOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkOrders();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkOrders();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditTrailForEntity(arg0: EntityType, arg1: string): Promise<Array<AuditEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditTrailForEntity(to_candid_EntityType_n45(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditTrailForEntity(to_candid_EntityType_n45(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditTrailForUser(arg0: Principal): Promise<Array<AuditEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditTrailForUser(arg0);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditTrailForUser(arg0);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkOrder(arg0: string): Promise<WorkOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkOrder(arg0);
                return from_candid_WorkOrder_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkOrder(arg0);
            return from_candid_WorkOrder_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async reportDeviation(arg0: {
        title: string;
        description: string;
        batchRecordId: string;
        severity: DeviationSeverity;
    }): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.reportDeviation(to_candid_record_n57(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportDeviation(to_candid_record_n57(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n60(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n60(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBatchStatus(arg0: string, arg1: BatchStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBatchStatus(arg0, to_candid_BatchStatus_n62(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBatchStatus(arg0, to_candid_BatchStatus_n62(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateEquipmentStatus(arg0: string, arg1: EquipmentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEquipmentStatus(arg0, to_candid_EquipmentStatus_n64(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEquipmentStatus(arg0, to_candid_EquipmentStatus_n64(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateWorkOrderStatus(arg0: string, arg1: WorkOrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkOrderStatus(arg0, to_candid_WorkOrderStatus_n66(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkOrderStatus(arg0, to_candid_WorkOrderStatus_n66(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AuditEvent_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditEvent): AuditEvent {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_BatchRecord_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BatchRecord): BatchRecord {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_BatchStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BatchStatus): BatchStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_DeviationSeverity_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeviationSeverity): DeviationSeverity {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_DeviationStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeviationStatus): DeviationStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Deviation_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Deviation): Deviation {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_EntityType_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EntityType): EntityType {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_EquipmentStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EquipmentStatus): EquipmentStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Equipment_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Equipment): Equipment {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_MaterialStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaterialStatus): MaterialStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Material_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Material): Material {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_PersonnelPure_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersonnelPure): PersonnelPure {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_PersonnelRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersonnelRole): PersonnelRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_WorkOrderStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkOrderStatus): WorkOrderStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_WorkOrder_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkOrder): WorkOrder {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    status: _BatchStatus;
    unit: string;
    productName: string;
    operatorId: Principal;
    notes: string;
    batchId: string;
    currentStage: string;
    batchSize: number;
}): {
    startTime: bigint;
    status: BatchStatus;
    unit: string;
    productName: string;
    operatorId: Principal;
    notes: string;
    batchId: string;
    currentStage: string;
    batchSize: number;
} {
    return {
        startTime: value.startTime,
        status: from_candid_BatchStatus_n16(_uploadFile, _downloadFile, value.status),
        unit: value.unit,
        productName: value.productName,
        operatorId: value.operatorId,
        notes: value.notes,
        batchId: value.batchId,
        currentStage: value.currentStage,
        batchSize: value.batchSize
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    capaDescription: string;
    reportedDate: bigint;
    description: string;
    deviationStatus: _DeviationStatus;
    reportedBy: Principal;
    batchRecordId: string;
    severity: _DeviationSeverity;
    deviationId: string;
}): {
    title: string;
    capaDescription: string;
    reportedDate: bigint;
    description: string;
    deviationStatus: DeviationStatus;
    reportedBy: Principal;
    batchRecordId: string;
    severity: DeviationSeverity;
    deviationId: string;
} {
    return {
        title: value.title,
        capaDescription: value.capaDescription,
        reportedDate: value.reportedDate,
        description: value.description,
        deviationStatus: from_candid_DeviationStatus_n21(_uploadFile, _downloadFile, value.deviationStatus),
        reportedBy: value.reportedBy,
        batchRecordId: value.batchRecordId,
        severity: from_candid_DeviationSeverity_n23(_uploadFile, _downloadFile, value.severity),
        deviationId: value.deviationId
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _EquipmentStatus;
    lastMaintenance: bigint;
    name: string;
    equipmentType: string;
    notes: string;
    equipmentId: string;
    location: string;
}): {
    status: EquipmentStatus;
    lastMaintenance: bigint;
    name: string;
    equipmentType: string;
    notes: string;
    equipmentId: string;
    location: string;
} {
    return {
        status: from_candid_EquipmentStatus_n28(_uploadFile, _downloadFile, value.status),
        lastMaintenance: value.lastMaintenance,
        name: value.name,
        equipmentType: value.equipmentType,
        notes: value.notes,
        equipmentId: value.equipmentId,
        location: value.location
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiryDate: bigint;
    name: string;
    unit: string;
    materialId: string;
    lotNumber: string;
    materialStatus: _MaterialStatus;
    quantity: number;
    storageLocation: string;
}): {
    expiryDate: bigint;
    name: string;
    unit: string;
    materialId: string;
    lotNumber: string;
    materialStatus: MaterialStatus;
    quantity: number;
    storageLocation: string;
} {
    return {
        expiryDate: value.expiryDate,
        name: value.name,
        unit: value.unit,
        materialId: value.materialId,
        lotNumber: value.lotNumber,
        materialStatus: from_candid_MaterialStatus_n33(_uploadFile, _downloadFile, value.materialStatus),
        quantity: value.quantity,
        storageLocation: value.storageLocation
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _PersonnelRole;
    isActive: boolean;
    certifications: Array<string>;
    principalId: Principal;
}): {
    name: string;
    role: PersonnelRole;
    isActive: boolean;
    certifications: Array<string>;
    principalId: Principal;
} {
    return {
        name: value.name,
        role: from_candid_PersonnelRole_n38(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        certifications: value.certifications,
        principalId: value.principalId
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _WorkOrderStatus;
    scheduledStart: bigint;
    assignedTo: Principal;
    description: string;
    workOrderId: string;
    batchRecordId: string;
    priority: string;
}): {
    status: WorkOrderStatus;
    scheduledStart: bigint;
    assignedTo: Principal;
    description: string;
    workOrderId: string;
    batchRecordId: string;
    priority: string;
} {
    return {
        status: from_candid_WorkOrderStatus_n43(_uploadFile, _downloadFile, value.status),
        scheduledStart: value.scheduledStart,
        assignedTo: value.assignedTo,
        description: value.description,
        workOrderId: value.workOrderId,
        batchRecordId: value.batchRecordId,
        priority: value.priority
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eventId: string;
    action: string;
    userId: Principal;
    entityId: string;
    timestamp: bigint;
    details: string;
    entityType: _EntityType;
}): {
    eventId: string;
    action: string;
    userId: Principal;
    entityId: string;
    timestamp: bigint;
    details: string;
    entityType: EntityType;
} {
    return {
        eventId: value.eventId,
        action: value.action,
        userId: value.userId,
        entityId: value.entityId,
        timestamp: value.timestamp,
        details: value.details,
        entityType: from_candid_EntityType_n50(_uploadFile, _downloadFile, value.entityType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _PersonnelRole;
    isActive: boolean;
    certifications: Array<string>;
}): {
    name: string;
    role: PersonnelRole;
    isActive: boolean;
    certifications: Array<string>;
} {
    return {
        name: value.name,
        role: from_candid_PersonnelRole_n38(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        certifications: value.certifications
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    inProgress: null;
} | {
    onHold: null;
}): BatchStatus {
    return "pending" in value ? BatchStatus.pending : "completed" in value ? BatchStatus.completed : "rejected" in value ? BatchStatus.rejected : "inProgress" in value ? BatchStatus.inProgress : "onHold" in value ? BatchStatus.onHold : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
} | {
    underInvestigation: null;
}): DeviationStatus {
    return "closed" in value ? DeviationStatus.closed : "open" in value ? DeviationStatus.open : "underInvestigation" in value ? DeviationStatus.underInvestigation : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    major: null;
} | {
    minor: null;
} | {
    critical: null;
}): DeviationSeverity {
    return "major" in value ? DeviationSeverity.major : "minor" in value ? DeviationSeverity.minor : "critical" in value ? DeviationSeverity.critical : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cleaning: null;
} | {
    available: null;
} | {
    maintenance: null;
} | {
    inUse: null;
}): EquipmentStatus {
    return "cleaning" in value ? EquipmentStatus.cleaning : "available" in value ? EquipmentStatus.available : "maintenance" in value ? EquipmentStatus.maintenance : "inUse" in value ? EquipmentStatus.inUse : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    released: null;
} | {
    consumed: null;
} | {
    rejected: null;
} | {
    quarantine: null;
}): MaterialStatus {
    return "released" in value ? MaterialStatus.released : "consumed" in value ? MaterialStatus.consumed : "rejected" in value ? MaterialStatus.rejected : "quarantine" in value ? MaterialStatus.quarantine : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    productionManager: null;
} | {
    operator: null;
} | {
    qaInspector: null;
}): PersonnelRole {
    return "admin" in value ? PersonnelRole.admin : "productionManager" in value ? PersonnelRole.productionManager : "operator" in value ? PersonnelRole.operator : "qaInspector" in value ? PersonnelRole.qaInspector : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    open: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): WorkOrderStatus {
    return "cancelled" in value ? WorkOrderStatus.cancelled : "open" in value ? WorkOrderStatus.open : "completed" in value ? WorkOrderStatus.completed : "inProgress" in value ? WorkOrderStatus.inProgress : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    equipment: null;
} | {
    deviation: null;
} | {
    personnel: null;
} | {
    workOrder: null;
} | {
    material: null;
} | {
    batchRecord: null;
}): EntityType {
    return "equipment" in value ? EntityType.equipment : "deviation" in value ? EntityType.deviation : "personnel" in value ? EntityType.personnel : "workOrder" in value ? EntityType.workOrder : "material" in value ? EntityType.material : "batchRecord" in value ? EntityType.batchRecord : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BatchRecord>): Array<BatchRecord> {
    return value.map((x)=>from_candid_BatchRecord_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Deviation>): Array<Deviation> {
    return value.map((x)=>from_candid_Deviation_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Equipment>): Array<Equipment> {
    return value.map((x)=>from_candid_Equipment_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Material>): Array<Material> {
    return value.map((x)=>from_candid_Material_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PersonnelPure>): Array<PersonnelPure> {
    return value.map((x)=>from_candid_PersonnelPure_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkOrder>): Array<WorkOrder> {
    return value.map((x)=>from_candid_WorkOrder_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditEvent>): Array<AuditEvent> {
    return value.map((x)=>from_candid_AuditEvent_n48(_uploadFile, _downloadFile, x));
}
function to_candid_BatchStatus_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BatchStatus): _BatchStatus {
    return to_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function to_candid_DeviationSeverity_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeviationSeverity): _DeviationSeverity {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function to_candid_EntityType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntityType): _EntityType {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_EquipmentStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentStatus): _EquipmentStatus {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function to_candid_PersonnelRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonnelRole): _PersonnelRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_WorkOrderStatus_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkOrderStatus): _WorkOrderStatus {
    return to_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    batchRecordId: string;
    severity: DeviationSeverity;
}): {
    title: string;
    description: string;
    batchRecordId: string;
    severity: _DeviationSeverity;
} {
    return {
        title: value.title,
        description: value.description,
        batchRecordId: value.batchRecordId,
        severity: to_candid_DeviationSeverity_n58(_uploadFile, _downloadFile, value.severity)
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: PersonnelRole;
    isActive: boolean;
    certifications: Array<string>;
}): {
    name: string;
    role: _PersonnelRole;
    isActive: boolean;
    certifications: Array<string>;
} {
    return {
        name: value.name,
        role: to_candid_PersonnelRole_n9(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        certifications: value.certifications
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: PersonnelRole;
    certifications: Array<string>;
    principalId: Principal;
}): {
    name: string;
    role: _PersonnelRole;
    certifications: Array<string>;
    principalId: Principal;
} {
    return {
        name: value.name,
        role: to_candid_PersonnelRole_n9(_uploadFile, _downloadFile, value.role),
        certifications: value.certifications,
        principalId: value.principalId
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonnelRole): {
    admin: null;
} | {
    productionManager: null;
} | {
    operator: null;
} | {
    qaInspector: null;
} {
    return value == PersonnelRole.admin ? {
        admin: null
    } : value == PersonnelRole.productionManager ? {
        productionManager: null
    } : value == PersonnelRole.operator ? {
        operator: null
    } : value == PersonnelRole.qaInspector ? {
        qaInspector: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntityType): {
    equipment: null;
} | {
    deviation: null;
} | {
    personnel: null;
} | {
    workOrder: null;
} | {
    material: null;
} | {
    batchRecord: null;
} {
    return value == EntityType.equipment ? {
        equipment: null
    } : value == EntityType.deviation ? {
        deviation: null
    } : value == EntityType.personnel ? {
        personnel: null
    } : value == EntityType.workOrder ? {
        workOrder: null
    } : value == EntityType.material ? {
        material: null
    } : value == EntityType.batchRecord ? {
        batchRecord: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeviationSeverity): {
    major: null;
} | {
    minor: null;
} | {
    critical: null;
} {
    return value == DeviationSeverity.major ? {
        major: null
    } : value == DeviationSeverity.minor ? {
        minor: null
    } : value == DeviationSeverity.critical ? {
        critical: null
    } : value;
}
function to_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BatchStatus): {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    inProgress: null;
} | {
    onHold: null;
} {
    return value == BatchStatus.pending ? {
        pending: null
    } : value == BatchStatus.completed ? {
        completed: null
    } : value == BatchStatus.rejected ? {
        rejected: null
    } : value == BatchStatus.inProgress ? {
        inProgress: null
    } : value == BatchStatus.onHold ? {
        onHold: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentStatus): {
    cleaning: null;
} | {
    available: null;
} | {
    maintenance: null;
} | {
    inUse: null;
} {
    return value == EquipmentStatus.cleaning ? {
        cleaning: null
    } : value == EquipmentStatus.available ? {
        available: null
    } : value == EquipmentStatus.maintenance ? {
        maintenance: null
    } : value == EquipmentStatus.inUse ? {
        inUse: null
    } : value;
}
function to_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkOrderStatus): {
    cancelled: null;
} | {
    open: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == WorkOrderStatus.cancelled ? {
        cancelled: null
    } : value == WorkOrderStatus.open ? {
        open: null
    } : value == WorkOrderStatus.completed ? {
        completed: null
    } : value == WorkOrderStatus.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
